// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: notification/notification.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	EmailType     string                 `protobuf:"bytes,2,opt,name=email_type,json=emailType,proto3" json:"email_type,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendEmailRequest) GetEmailType() string {
	if x != nil {
		return x.EmailType
	}
	return ""
}

func (x *SendEmailRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetDeliveryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryStatusRequest) Reset() {
	*x = GetDeliveryStatusRequest{}
	mi := &file_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryStatusRequest) ProtoMessage() {}

func (x *GetDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeliveryStatusRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type GetDeliveryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	DeliveredAt   string                 `protobuf:"bytes,3,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryStatusResponse) Reset() {
	*x = GetDeliveryStatusResponse{}
	mi := &file_notification_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryStatusResponse) ProtoMessage() {}

func (x *GetDeliveryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryStatusResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeliveryStatusResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetDeliveryStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetDeliveryStatusResponse) GetDeliveredAt() string {
	if x != nil {
		return x.DeliveredAt
	}
	return ""
}

type GetPendingMobileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingMobileRequest) Reset() {
	*x = GetPendingMobileRequest{}
	mi := &file_notification_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingMobileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingMobileRequest) ProtoMessage() {}

func (x *GetPendingMobileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingMobileRequest.ProtoReflect.Descriptor instead.
func (*GetPendingMobileRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetPendingMobileRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MobileInboxEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChallengeId   uint64                 `protobuf:"varint,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	DisplayData   string                 `protobuf:"bytes,4,opt,name=display_data,json=displayData,proto3" json:"display_data,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MobileInboxEntry) Reset() {
	*x = MobileInboxEntry{}
	mi := &file_notification_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MobileInboxEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MobileInboxEntry) ProtoMessage() {}

func (x *MobileInboxEntry) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MobileInboxEntry.ProtoReflect.Descriptor instead.
func (*MobileInboxEntry) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{5}
}

func (x *MobileInboxEntry) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MobileInboxEntry) GetChallengeId() uint64 {
	if x != nil {
		return x.ChallengeId
	}
	return 0
}

func (x *MobileInboxEntry) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MobileInboxEntry) GetDisplayData() string {
	if x != nil {
		return x.DisplayData
	}
	return ""
}

func (x *MobileInboxEntry) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type PendingMobileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MobileInboxEntry    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingMobileResponse) Reset() {
	*x = PendingMobileResponse{}
	mi := &file_notification_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingMobileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingMobileResponse) ProtoMessage() {}

func (x *PendingMobileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingMobileResponse.ProtoReflect.Descriptor instead.
func (*PendingMobileResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{6}
}

func (x *PendingMobileResponse) GetItems() []*MobileInboxEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

type AckMobileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMobileRequest) Reset() {
	*x = AckMobileRequest{}
	mi := &file_notification_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMobileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMobileRequest) ProtoMessage() {}

func (x *AckMobileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMobileRequest.ProtoReflect.Descriptor instead.
func (*AckMobileRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{7}
}

func (x *AckMobileRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AckMobileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMobileResponse) Reset() {
	*x = AckMobileResponse{}
	mi := &file_notification_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMobileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMobileResponse) ProtoMessage() {}

func (x *AckMobileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMobileResponse.ProtoReflect.Descriptor instead.
func (*AckMobileResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{8}
}

func (x *AckMobileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ReadFilter    string                 `protobuf:"bytes,4,opt,name=read_filter,json=readFilter,proto3" json:"read_filter,omitempty"` // "", "read", "unread"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_notification_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{9}
}

func (x *ListNotificationsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListNotificationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNotificationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNotificationsRequest) GetReadFilter() string {
	if x != nil {
		return x.ReadFilter
	}
	return ""
}

type NotificationEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	IsRead        bool                   `protobuf:"varint,5,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	RefType       string                 `protobuf:"bytes,6,opt,name=ref_type,json=refType,proto3" json:"ref_type,omitempty"`
	RefId         uint64                 `protobuf:"varint,7,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationEntry) Reset() {
	*x = NotificationEntry{}
	mi := &file_notification_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationEntry) ProtoMessage() {}

func (x *NotificationEntry) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationEntry.ProtoReflect.Descriptor instead.
func (*NotificationEntry) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{10}
}

func (x *NotificationEntry) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotificationEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationEntry) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *NotificationEntry) GetRefType() string {
	if x != nil {
		return x.RefType
	}
	return ""
}

func (x *NotificationEntry) GetRefId() uint64 {
	if x != nil {
		return x.RefId
	}
	return 0
}

func (x *NotificationEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*NotificationEntry   `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_notification_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{11}
}

func (x *ListNotificationsResponse) GetNotifications() []*NotificationEntry {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_notification_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{12}
}

func (x *GetUnreadCountRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_notification_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{13}
}

func (x *GetUnreadCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MarkNotificationReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkNotificationReadRequest) Reset() {
	*x = MarkNotificationReadRequest{}
	mi := &file_notification_notification_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationReadRequest) ProtoMessage() {}

func (x *MarkNotificationReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationReadRequest.ProtoReflect.Descriptor instead.
func (*MarkNotificationReadRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{14}
}

func (x *MarkNotificationReadRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MarkNotificationReadRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MarkNotificationReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkNotificationReadResponse) Reset() {
	*x = MarkNotificationReadResponse{}
	mi := &file_notification_notification_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationReadResponse) ProtoMessage() {}

func (x *MarkNotificationReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationReadResponse.ProtoReflect.Descriptor instead.
func (*MarkNotificationReadResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{15}
}

func (x *MarkNotificationReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MarkAllNotificationsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllNotificationsReadRequest) Reset() {
	*x = MarkAllNotificationsReadRequest{}
	mi := &file_notification_notification_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllNotificationsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllNotificationsReadRequest) ProtoMessage() {}

func (x *MarkAllNotificationsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllNotificationsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllNotificationsReadRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{16}
}

func (x *MarkAllNotificationsReadRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MarkAllNotificationsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllNotificationsReadResponse) Reset() {
	*x = MarkAllNotificationsReadResponse{}
	mi := &file_notification_notification_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllNotificationsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllNotificationsReadResponse) ProtoMessage() {}

func (x *MarkAllNotificationsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllNotificationsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAllNotificationsReadResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{17}
}

func (x *MarkAllNotificationsReadResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TemplateVariable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Example       string                 `protobuf:"bytes,3,opt,name=example,proto3" json:"example,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateVariable) Reset() {
	*x = TemplateVariable{}
	mi := &file_notification_notification_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateVariable) ProtoMessage() {}

func (x *TemplateVariable) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateVariable.ProtoReflect.Descriptor instead.
func (*TemplateVariable) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{18}
}

func (x *TemplateVariable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateVariable) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TemplateVariable) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

type TemplateInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Channel        string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Variables      []*TemplateVariable    `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty"`
	DefaultSubject string                 `protobuf:"bytes,5,opt,name=default_subject,json=defaultSubject,proto3" json:"default_subject,omitempty"`
	DefaultBody    string                 `protobuf:"bytes,6,opt,name=default_body,json=defaultBody,proto3" json:"default_body,omitempty"`
	CurrentSubject string                 `protobuf:"bytes,7,opt,name=current_subject,json=currentSubject,proto3" json:"current_subject,omitempty"`
	CurrentBody    string                 `protobuf:"bytes,8,opt,name=current_body,json=currentBody,proto3" json:"current_body,omitempty"`
	IsCustomized   bool                   `protobuf:"varint,9,opt,name=is_customized,json=isCustomized,proto3" json:"is_customized,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TemplateInfo) Reset() {
	*x = TemplateInfo{}
	mi := &file_notification_notification_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateInfo) ProtoMessage() {}

func (x *TemplateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateInfo.ProtoReflect.Descriptor instead.
func (*TemplateInfo) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{19}
}

func (x *TemplateInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TemplateInfo) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *TemplateInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TemplateInfo) GetVariables() []*TemplateVariable {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *TemplateInfo) GetDefaultSubject() string {
	if x != nil {
		return x.DefaultSubject
	}
	return ""
}

func (x *TemplateInfo) GetDefaultBody() string {
	if x != nil {
		return x.DefaultBody
	}
	return ""
}

func (x *TemplateInfo) GetCurrentSubject() string {
	if x != nil {
		return x.CurrentSubject
	}
	return ""
}

func (x *TemplateInfo) GetCurrentBody() string {
	if x != nil {
		return x.CurrentBody
	}
	return ""
}

func (x *TemplateInfo) GetIsCustomized() bool {
	if x != nil {
		return x.IsCustomized
	}
	return false
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"` // "" = all, "email", or "push"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_notification_notification_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{20}
}

func (x *ListTemplatesRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*TemplateInfo        `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_notification_notification_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{21}
}

func (x *ListTemplatesResponse) GetTemplates() []*TemplateInfo {
	if x != nil {
		return x.Templates
	}
	return nil
}

type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_notification_notification_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{22}
}

func (x *GetTemplateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetTemplateRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type SetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	UpdatedBy     uint64                 `protobuf:"varint,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTemplateRequest) Reset() {
	*x = SetTemplateRequest{}
	mi := &file_notification_notification_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTemplateRequest) ProtoMessage() {}

func (x *SetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTemplateRequest.ProtoReflect.Descriptor instead.
func (*SetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{23}
}

func (x *SetTemplateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SetTemplateRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SetTemplateRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SetTemplateRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SetTemplateRequest) GetUpdatedBy() uint64 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

type ResetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetTemplateRequest) Reset() {
	*x = ResetTemplateRequest{}
	mi := &file_notification_notification_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetTemplateRequest) ProtoMessage() {}

func (x *ResetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetTemplateRequest.ProtoReflect.Descriptor instead.
func (*ResetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{24}
}

func (x *ResetTemplateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResetTemplateRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type ListAdminAuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Since         int64                  `protobuf:"varint,3,opt,name=since,proto3" json:"since,omitempty"`                    // unix seconds, 0 = no lower bound
	Until         int64                  `protobuf:"varint,4,opt,name=until,proto3" json:"until,omitempty"`                    // unix seconds, 0 = no upper bound
	ActorId       int64                  `protobuf:"varint,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"` // employee_id filter, 0 = all
	Action        string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`                   // exact match, "" = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminAuditLogsRequest) Reset() {
	*x = ListAdminAuditLogsRequest{}
	mi := &file_notification_notification_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminAuditLogsRequest) ProtoMessage() {}

func (x *ListAdminAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*ListAdminAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{25}
}

func (x *ListAdminAuditLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAdminAuditLogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAdminAuditLogsRequest) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

func (x *ListAdminAuditLogsRequest) GetUntil() int64 {
	if x != nil {
		return x.Until
	}
	return 0
}

func (x *ListAdminAuditLogsRequest) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *ListAdminAuditLogsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type AdminAuditLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	CronName      string                 `protobuf:"bytes,4,opt,name=cron_name,json=cronName,proto3" json:"cron_name,omitempty"`
	EmployeeId    int64                  `protobuf:"varint,5,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAuditLogEntry) Reset() {
	*x = AdminAuditLogEntry{}
	mi := &file_notification_notification_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAuditLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAuditLogEntry) ProtoMessage() {}

func (x *AdminAuditLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAuditLogEntry.ProtoReflect.Descriptor instead.
func (*AdminAuditLogEntry) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{26}
}

func (x *AdminAuditLogEntry) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminAuditLogEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AdminAuditLogEntry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *AdminAuditLogEntry) GetCronName() string {
	if x != nil {
		return x.CronName
	}
	return ""
}

func (x *AdminAuditLogEntry) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *AdminAuditLogEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AdminAuditLogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ListAdminAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AdminAuditLogEntry  `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminAuditLogsResponse) Reset() {
	*x = ListAdminAuditLogsResponse{}
	mi := &file_notification_notification_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminAuditLogsResponse) ProtoMessage() {}

func (x *ListAdminAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*ListAdminAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{27}
}

func (x *ListAdminAuditLogsResponse) GetEntries() []*AdminAuditLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListAdminAuditLogsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAdminAuditLogsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAdminAuditLogsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_notification_notification_proto protoreflect.FileDescriptor

const file_notification_notification_proto_rawDesc = "" +
	"\n" +
	"\x1fnotification/notification.proto\x12\fnotification\"\xb8\x01\n" +
	"\x10SendEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x1d\n" +
	"\n" +
	"email_type\x18\x02 \x01(\tR\temailType\x12<\n" +
	"\x04data\x18\x03 \x03(\v2(.notification.SendEmailRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x11SendEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\x18GetDeliveryStatusRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"u\n" +
	"\x19GetDeliveryStatusResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fdelivered_at\x18\x03 \x01(\tR\vdeliveredAt\"2\n" +
	"\x17GetPendingMobileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x9f\x01\n" +
	"\x10MobileInboxEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fchallenge_id\x18\x02 \x01(\x04R\vchallengeId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12!\n" +
	"\fdisplay_data\x18\x04 \x01(\tR\vdisplayData\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tR\texpiresAt\"M\n" +
	"\x15PendingMobileResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.notification.MobileInboxEntryR\x05items\"\"\n" +
	"\x10AckMobileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"-\n" +
	"\x11AckMobileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x85\x01\n" +
	"\x18ListNotificationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vread_filter\x18\x04 \x01(\tR\n" +
	"readFilter\"\xd1\x01\n" +
	"\x11NotificationEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x17\n" +
	"\ais_read\x18\x05 \x01(\bR\x06isRead\x12\x19\n" +
	"\bref_type\x18\x06 \x01(\tR\arefType\x12\x15\n" +
	"\x06ref_id\x18\a \x01(\x04R\x05refId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"x\n" +
	"\x19ListNotificationsResponse\x12E\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1f.notification.NotificationEntryR\rnotifications\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"0\n" +
	"\x15GetUnreadCountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\".\n" +
	"\x16GetUnreadCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"F\n" +
	"\x1bMarkNotificationReadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"8\n" +
	"\x1cMarkNotificationReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\":\n" +
	"\x1fMarkAllNotificationsReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"8\n" +
	" MarkAllNotificationsReadResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"b\n" +
	"\x10TemplateVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aexample\x18\x03 \x01(\tR\aexample\"\xd9\x02\n" +
	"\fTemplateInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12<\n" +
	"\tvariables\x18\x04 \x03(\v2\x1e.notification.TemplateVariableR\tvariables\x12'\n" +
	"\x0fdefault_subject\x18\x05 \x01(\tR\x0edefaultSubject\x12!\n" +
	"\fdefault_body\x18\x06 \x01(\tR\vdefaultBody\x12'\n" +
	"\x0fcurrent_subject\x18\a \x01(\tR\x0ecurrentSubject\x12!\n" +
	"\fcurrent_body\x18\b \x01(\tR\vcurrentBody\x12#\n" +
	"\ris_customized\x18\t \x01(\bR\fisCustomized\"0\n" +
	"\x14ListTemplatesRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\"Q\n" +
	"\x15ListTemplatesResponse\x128\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1a.notification.TemplateInfoR\ttemplates\"B\n" +
	"\x12GetTemplateRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\"\x8f\x01\n" +
	"\x12SetTemplateRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x05 \x01(\x04R\tupdatedBy\"D\n" +
	"\x14ResetTemplateRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\"\xab\x01\n" +
	"\x19ListAdminAuditLogsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05since\x18\x03 \x01(\x03R\x05since\x12\x14\n" +
	"\x05until\x18\x04 \x01(\x03R\x05until\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\x03R\aactorId\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\"\xca\x01\n" +
	"\x12AdminAuditLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x1b\n" +
	"\tcron_name\x18\x04 \x01(\tR\bcronName\x12\x1f\n" +
	"\vemployee_id\x18\x05 \x01(\x03R\n" +
	"employeeId\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"\x9f\x01\n" +
	"\x1aListAdminAuditLogsResponse\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .notification.AdminAuditLogEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize2\xdb\t\n" +
	"\x13NotificationService\x12L\n" +
	"\tSendEmail\x12\x1e.notification.SendEmailRequest\x1a\x1f.notification.SendEmailResponse\x12d\n" +
	"\x11GetDeliveryStatus\x12&.notification.GetDeliveryStatusRequest\x1a'.notification.GetDeliveryStatusResponse\x12c\n" +
	"\x15GetPendingMobileItems\x12%.notification.GetPendingMobileRequest\x1a#.notification.PendingMobileResponse\x12P\n" +
	"\rAckMobileItem\x12\x1e.notification.AckMobileRequest\x1a\x1f.notification.AckMobileResponse\x12d\n" +
	"\x11ListNotifications\x12&.notification.ListNotificationsRequest\x1a'.notification.ListNotificationsResponse\x12[\n" +
	"\x0eGetUnreadCount\x12#.notification.GetUnreadCountRequest\x1a$.notification.GetUnreadCountResponse\x12m\n" +
	"\x14MarkNotificationRead\x12).notification.MarkNotificationReadRequest\x1a*.notification.MarkNotificationReadResponse\x12y\n" +
	"\x18MarkAllNotificationsRead\x12-.notification.MarkAllNotificationsReadRequest\x1a..notification.MarkAllNotificationsReadResponse\x12X\n" +
	"\rListTemplates\x12\".notification.ListTemplatesRequest\x1a#.notification.ListTemplatesResponse\x12K\n" +
	"\vGetTemplate\x12 .notification.GetTemplateRequest\x1a\x1a.notification.TemplateInfo\x12K\n" +
	"\vSetTemplate\x12 .notification.SetTemplateRequest\x1a\x1a.notification.TemplateInfo\x12O\n" +
	"\rResetTemplate\x12\".notification.ResetTemplateRequest\x1a\x1a.notification.TemplateInfo\x12g\n" +
	"\x12ListAdminAuditLogs\x12'.notification.ListAdminAuditLogsRequest\x1a(.notification.ListAdminAuditLogsResponseB;Z9github.com/exbanka/contract/notificationpb;notificationpbb\x06proto3"

var (
	file_notification_notification_proto_rawDescOnce sync.Once
	file_notification_notification_proto_rawDescData []byte
)

func file_notification_notification_proto_rawDescGZIP() []byte {
	file_notification_notification_proto_rawDescOnce.Do(func() {
		file_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)))
	})
	return file_notification_notification_proto_rawDescData
}

var file_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_notification_notification_proto_goTypes = []any{
	(*SendEmailRequest)(nil),                 // 0: notification.SendEmailRequest
	(*SendEmailResponse)(nil),                // 1: notification.SendEmailResponse
	(*GetDeliveryStatusRequest)(nil),         // 2: notification.GetDeliveryStatusRequest
	(*GetDeliveryStatusResponse)(nil),        // 3: notification.GetDeliveryStatusResponse
	(*GetPendingMobileRequest)(nil),          // 4: notification.GetPendingMobileRequest
	(*MobileInboxEntry)(nil),                 // 5: notification.MobileInboxEntry
	(*PendingMobileResponse)(nil),            // 6: notification.PendingMobileResponse
	(*AckMobileRequest)(nil),                 // 7: notification.AckMobileRequest
	(*AckMobileResponse)(nil),                // 8: notification.AckMobileResponse
	(*ListNotificationsRequest)(nil),         // 9: notification.ListNotificationsRequest
	(*NotificationEntry)(nil),                // 10: notification.NotificationEntry
	(*ListNotificationsResponse)(nil),        // 11: notification.ListNotificationsResponse
	(*GetUnreadCountRequest)(nil),            // 12: notification.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil),           // 13: notification.GetUnreadCountResponse
	(*MarkNotificationReadRequest)(nil),      // 14: notification.MarkNotificationReadRequest
	(*MarkNotificationReadResponse)(nil),     // 15: notification.MarkNotificationReadResponse
	(*MarkAllNotificationsReadRequest)(nil),  // 16: notification.MarkAllNotificationsReadRequest
	(*MarkAllNotificationsReadResponse)(nil), // 17: notification.MarkAllNotificationsReadResponse
	(*TemplateVariable)(nil),                 // 18: notification.TemplateVariable
	(*TemplateInfo)(nil),                     // 19: notification.TemplateInfo
	(*ListTemplatesRequest)(nil),             // 20: notification.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),            // 21: notification.ListTemplatesResponse
	(*GetTemplateRequest)(nil),               // 22: notification.GetTemplateRequest
	(*SetTemplateRequest)(nil),               // 23: notification.SetTemplateRequest
	(*ResetTemplateRequest)(nil),             // 24: notification.ResetTemplateRequest
	(*ListAdminAuditLogsRequest)(nil),        // 25: notification.ListAdminAuditLogsRequest
	(*AdminAuditLogEntry)(nil),               // 26: notification.AdminAuditLogEntry
	(*ListAdminAuditLogsResponse)(nil),       // 27: notification.ListAdminAuditLogsResponse
	nil,                                      // 28: notification.SendEmailRequest.DataEntry
}
var file_notification_notification_proto_depIdxs = []int32{
	28, // 0: notification.SendEmailRequest.data:type_name -> notification.SendEmailRequest.DataEntry
	5,  // 1: notification.PendingMobileResponse.items:type_name -> notification.MobileInboxEntry
	10, // 2: notification.ListNotificationsResponse.notifications:type_name -> notification.NotificationEntry
	18, // 3: notification.TemplateInfo.variables:type_name -> notification.TemplateVariable
	19, // 4: notification.ListTemplatesResponse.templates:type_name -> notification.TemplateInfo
	26, // 5: notification.ListAdminAuditLogsResponse.entries:type_name -> notification.AdminAuditLogEntry
	0,  // 6: notification.NotificationService.SendEmail:input_type -> notification.SendEmailRequest
	2,  // 7: notification.NotificationService.GetDeliveryStatus:input_type -> notification.GetDeliveryStatusRequest
	4,  // 8: notification.NotificationService.GetPendingMobileItems:input_type -> notification.GetPendingMobileRequest
	7,  // 9: notification.NotificationService.AckMobileItem:input_type -> notification.AckMobileRequest
	9,  // 10: notification.NotificationService.ListNotifications:input_type -> notification.ListNotificationsRequest
	12, // 11: notification.NotificationService.GetUnreadCount:input_type -> notification.GetUnreadCountRequest
	14, // 12: notification.NotificationService.MarkNotificationRead:input_type -> notification.MarkNotificationReadRequest
	16, // 13: notification.NotificationService.MarkAllNotificationsRead:input_type -> notification.MarkAllNotificationsReadRequest
	20, // 14: notification.NotificationService.ListTemplates:input_type -> notification.ListTemplatesRequest
	22, // 15: notification.NotificationService.GetTemplate:input_type -> notification.GetTemplateRequest
	23, // 16: notification.NotificationService.SetTemplate:input_type -> notification.SetTemplateRequest
	24, // 17: notification.NotificationService.ResetTemplate:input_type -> notification.ResetTemplateRequest
	25, // 18: notification.NotificationService.ListAdminAuditLogs:input_type -> notification.ListAdminAuditLogsRequest
	1,  // 19: notification.NotificationService.SendEmail:output_type -> notification.SendEmailResponse
	3,  // 20: notification.NotificationService.GetDeliveryStatus:output_type -> notification.GetDeliveryStatusResponse
	6,  // 21: notification.NotificationService.GetPendingMobileItems:output_type -> notification.PendingMobileResponse
	8,  // 22: notification.NotificationService.AckMobileItem:output_type -> notification.AckMobileResponse
	11, // 23: notification.NotificationService.ListNotifications:output_type -> notification.ListNotificationsResponse
	13, // 24: notification.NotificationService.GetUnreadCount:output_type -> notification.GetUnreadCountResponse
	15, // 25: notification.NotificationService.MarkNotificationRead:output_type -> notification.MarkNotificationReadResponse
	17, // 26: notification.NotificationService.MarkAllNotificationsRead:output_type -> notification.MarkAllNotificationsReadResponse
	21, // 27: notification.NotificationService.ListTemplates:output_type -> notification.ListTemplatesResponse
	19, // 28: notification.NotificationService.GetTemplate:output_type -> notification.TemplateInfo
	19, // 29: notification.NotificationService.SetTemplate:output_type -> notification.TemplateInfo
	19, // 30: notification.NotificationService.ResetTemplate:output_type -> notification.TemplateInfo
	27, // 31: notification.NotificationService.ListAdminAuditLogs:output_type -> notification.ListAdminAuditLogsResponse
	19, // [19:32] is the sub-list for method output_type
	6,  // [6:19] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_notification_notification_proto_init() }
func file_notification_notification_proto_init() {
	if File_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_notification_proto_goTypes,
		DependencyIndexes: file_notification_notification_proto_depIdxs,
		MessageInfos:      file_notification_notification_proto_msgTypes,
	}.Build()
	File_notification_notification_proto = out.File
	file_notification_notification_proto_goTypes = nil
	file_notification_notification_proto_depIdxs = nil
}
