// Code generated by perm-codegen. DO NOT EDIT.
package permissions

var Catalog = []Permission{
	"clients.create.any",
	"clients.read.all",
	"clients.read.assigned",
	"clients.read.own",
	"clients.update.profile",
	"clients.update.contact",
	"clients.update.limits",
	"accounts.create.current",
	"accounts.create.foreign",
	"accounts.read.all",
	"accounts.read.own",
	"accounts.update.name",
	"accounts.update.limits",
	"accounts.deactivate.any",
	"bank_accounts.manage.any",
	"peer_banks.manage.any",
	"cards.create.physical",
	"cards.create.virtual",
	"cards.read.all",
	"cards.read.own",
	"cards.block.any",
	"cards.unblock.any",
	"cards.approve.physical",
	"cards.approve.virtual",
	"credits.read.all",
	"credits.read.own",
	"credits.approve.cash",
	"credits.approve.housing",
	"credits.disburse.any",
	"orders.read.all",
	"orders.read.own",
	"orders.place.own",
	"orders.place.on_behalf_client",
	"orders.place.on_behalf_bank",
	"orders.cancel.own",
	"orders.cancel.all",
	"securities.read.holdings_all",
	"securities.read.holdings_own",
	"securities.manage.catalog",
	"securities.trade.any",
	"otc.trade.accept",
	"otc.trade.exercise",
	"otc.trade.expire",
	"otc.trade.on_behalf",
	"otc.read.all",
	"funds.invest.own",
	"funds.invest.on_behalf_client",
	"funds.invest.on_behalf_bank",
	"funds.redeem.own",
	"funds.read.all",
	"funds.manage.catalog",
	"actuaries.read.all",
	"actuaries.manage.any",
	"employees.create.any",
	"employees.read.all",
	"employees.update.any",
	"employees.roles.assign",
	"employees.permissions.assign",
	"employees.deactivate.any",
	"roles.read.all",
	"roles.update.any",
	"roles.permissions.assign",
	"roles.permissions.revoke",
	"limits.employee.read",
	"limits.employee.update",
	"limit_templates.create.any",
	"limit_templates.update.any",
	"fees.create.any",
	"fees.update.any",
	"verification.skip.any",
	"verification.manage.any",
	"exchange_rates.read.any",
	"exchange_rates.update.any",
	"notifications.templates.manage",
	"portfolio.view.client",
	"portfolio.view.fund",
	"admin.crons.view",
	"admin.crons.trigger",
	"admin.crons.manage",
	"admin.audit.view",
}

var Accounts = struct {
	Create struct {
		Current Permission
		Foreign Permission
	}
	Deactivate struct {
		Any Permission
	}
	Read struct {
		All Permission
		Own Permission
	}
	Update struct {
		Limits Permission
		Name   Permission
	}
}{
	Create: struct {
		Current Permission
		Foreign Permission
	}{
		Current: "accounts.create.current",
		Foreign: "accounts.create.foreign",
	},
	Deactivate: struct {
		Any Permission
	}{
		Any: "accounts.deactivate.any",
	},
	Read: struct {
		All Permission
		Own Permission
	}{
		All: "accounts.read.all",
		Own: "accounts.read.own",
	},
	Update: struct {
		Limits Permission
		Name   Permission
	}{
		Limits: "accounts.update.limits",
		Name:   "accounts.update.name",
	},
}

var Actuaries = struct {
	Manage struct {
		Any Permission
	}
	Read struct {
		All Permission
	}
}{
	Manage: struct {
		Any Permission
	}{
		Any: "actuaries.manage.any",
	},
	Read: struct {
		All Permission
	}{
		All: "actuaries.read.all",
	},
}

var Admin = struct {
	Audit struct {
		View Permission
	}
	Crons struct {
		Manage  Permission
		Trigger Permission
		View    Permission
	}
}{
	Audit: struct {
		View Permission
	}{
		View: "admin.audit.view",
	},
	Crons: struct {
		Manage  Permission
		Trigger Permission
		View    Permission
	}{
		Manage:  "admin.crons.manage",
		Trigger: "admin.crons.trigger",
		View:    "admin.crons.view",
	},
}

var BankAccounts = struct {
	Manage struct {
		Any Permission
	}
}{
	Manage: struct {
		Any Permission
	}{
		Any: "bank_accounts.manage.any",
	},
}

var Cards = struct {
	Approve struct {
		Physical Permission
		Virtual  Permission
	}
	Block struct {
		Any Permission
	}
	Create struct {
		Physical Permission
		Virtual  Permission
	}
	Read struct {
		All Permission
		Own Permission
	}
	Unblock struct {
		Any Permission
	}
}{
	Approve: struct {
		Physical Permission
		Virtual  Permission
	}{
		Physical: "cards.approve.physical",
		Virtual:  "cards.approve.virtual",
	},
	Block: struct {
		Any Permission
	}{
		Any: "cards.block.any",
	},
	Create: struct {
		Physical Permission
		Virtual  Permission
	}{
		Physical: "cards.create.physical",
		Virtual:  "cards.create.virtual",
	},
	Read: struct {
		All Permission
		Own Permission
	}{
		All: "cards.read.all",
		Own: "cards.read.own",
	},
	Unblock: struct {
		Any Permission
	}{
		Any: "cards.unblock.any",
	},
}

var Clients = struct {
	Create struct {
		Any Permission
	}
	Read struct {
		All      Permission
		Assigned Permission
		Own      Permission
	}
	Update struct {
		Contact Permission
		Limits  Permission
		Profile Permission
	}
}{
	Create: struct {
		Any Permission
	}{
		Any: "clients.create.any",
	},
	Read: struct {
		All      Permission
		Assigned Permission
		Own      Permission
	}{
		All:      "clients.read.all",
		Assigned: "clients.read.assigned",
		Own:      "clients.read.own",
	},
	Update: struct {
		Contact Permission
		Limits  Permission
		Profile Permission
	}{
		Contact: "clients.update.contact",
		Limits:  "clients.update.limits",
		Profile: "clients.update.profile",
	},
}

var Credits = struct {
	Approve struct {
		Cash    Permission
		Housing Permission
	}
	Disburse struct {
		Any Permission
	}
	Read struct {
		All Permission
		Own Permission
	}
}{
	Approve: struct {
		Cash    Permission
		Housing Permission
	}{
		Cash:    "credits.approve.cash",
		Housing: "credits.approve.housing",
	},
	Disburse: struct {
		Any Permission
	}{
		Any: "credits.disburse.any",
	},
	Read: struct {
		All Permission
		Own Permission
	}{
		All: "credits.read.all",
		Own: "credits.read.own",
	},
}

var Employees = struct {
	Create struct {
		Any Permission
	}
	Deactivate struct {
		Any Permission
	}
	Permissions struct {
		Assign Permission
	}
	Read struct {
		All Permission
	}
	Roles struct {
		Assign Permission
	}
	Update struct {
		Any Permission
	}
}{
	Create: struct {
		Any Permission
	}{
		Any: "employees.create.any",
	},
	Deactivate: struct {
		Any Permission
	}{
		Any: "employees.deactivate.any",
	},
	Permissions: struct {
		Assign Permission
	}{
		Assign: "employees.permissions.assign",
	},
	Read: struct {
		All Permission
	}{
		All: "employees.read.all",
	},
	Roles: struct {
		Assign Permission
	}{
		Assign: "employees.roles.assign",
	},
	Update: struct {
		Any Permission
	}{
		Any: "employees.update.any",
	},
}

var ExchangeRates = struct {
	Read struct {
		Any Permission
	}
	Update struct {
		Any Permission
	}
}{
	Read: struct {
		Any Permission
	}{
		Any: "exchange_rates.read.any",
	},
	Update: struct {
		Any Permission
	}{
		Any: "exchange_rates.update.any",
	},
}

var Fees = struct {
	Create struct {
		Any Permission
	}
	Update struct {
		Any Permission
	}
}{
	Create: struct {
		Any Permission
	}{
		Any: "fees.create.any",
	},
	Update: struct {
		Any Permission
	}{
		Any: "fees.update.any",
	},
}

var Funds = struct {
	Invest struct {
		OnBehalfBank   Permission
		OnBehalfClient Permission
		Own            Permission
	}
	Manage struct {
		Catalog Permission
	}
	Read struct {
		All Permission
	}
	Redeem struct {
		Own Permission
	}
}{
	Invest: struct {
		OnBehalfBank   Permission
		OnBehalfClient Permission
		Own            Permission
	}{
		OnBehalfBank:   "funds.invest.on_behalf_bank",
		OnBehalfClient: "funds.invest.on_behalf_client",
		Own:            "funds.invest.own",
	},
	Manage: struct {
		Catalog Permission
	}{
		Catalog: "funds.manage.catalog",
	},
	Read: struct {
		All Permission
	}{
		All: "funds.read.all",
	},
	Redeem: struct {
		Own Permission
	}{
		Own: "funds.redeem.own",
	},
}

var LimitTemplates = struct {
	Create struct {
		Any Permission
	}
	Update struct {
		Any Permission
	}
}{
	Create: struct {
		Any Permission
	}{
		Any: "limit_templates.create.any",
	},
	Update: struct {
		Any Permission
	}{
		Any: "limit_templates.update.any",
	},
}

var Limits = struct {
	Employee struct {
		Read   Permission
		Update Permission
	}
}{
	Employee: struct {
		Read   Permission
		Update Permission
	}{
		Read:   "limits.employee.read",
		Update: "limits.employee.update",
	},
}

var Notifications = struct {
	Templates struct {
		Manage Permission
	}
}{
	Templates: struct {
		Manage Permission
	}{
		Manage: "notifications.templates.manage",
	},
}

var Orders = struct {
	Cancel struct {
		All Permission
		Own Permission
	}
	Place struct {
		OnBehalfBank   Permission
		OnBehalfClient Permission
		Own            Permission
	}
	Read struct {
		All Permission
		Own Permission
	}
}{
	Cancel: struct {
		All Permission
		Own Permission
	}{
		All: "orders.cancel.all",
		Own: "orders.cancel.own",
	},
	Place: struct {
		OnBehalfBank   Permission
		OnBehalfClient Permission
		Own            Permission
	}{
		OnBehalfBank:   "orders.place.on_behalf_bank",
		OnBehalfClient: "orders.place.on_behalf_client",
		Own:            "orders.place.own",
	},
	Read: struct {
		All Permission
		Own Permission
	}{
		All: "orders.read.all",
		Own: "orders.read.own",
	},
}

var Otc = struct {
	Read struct {
		All Permission
	}
	Trade struct {
		Accept   Permission
		Exercise Permission
		Expire   Permission
		OnBehalf Permission
	}
}{
	Read: struct {
		All Permission
	}{
		All: "otc.read.all",
	},
	Trade: struct {
		Accept   Permission
		Exercise Permission
		Expire   Permission
		OnBehalf Permission
	}{
		Accept:   "otc.trade.accept",
		Exercise: "otc.trade.exercise",
		Expire:   "otc.trade.expire",
		OnBehalf: "otc.trade.on_behalf",
	},
}

var PeerBanks = struct {
	Manage struct {
		Any Permission
	}
}{
	Manage: struct {
		Any Permission
	}{
		Any: "peer_banks.manage.any",
	},
}

var Portfolio = struct {
	View struct {
		Client Permission
		Fund   Permission
	}
}{
	View: struct {
		Client Permission
		Fund   Permission
	}{
		Client: "portfolio.view.client",
		Fund:   "portfolio.view.fund",
	},
}

var Roles = struct {
	Permissions struct {
		Assign Permission
		Revoke Permission
	}
	Read struct {
		All Permission
	}
	Update struct {
		Any Permission
	}
}{
	Permissions: struct {
		Assign Permission
		Revoke Permission
	}{
		Assign: "roles.permissions.assign",
		Revoke: "roles.permissions.revoke",
	},
	Read: struct {
		All Permission
	}{
		All: "roles.read.all",
	},
	Update: struct {
		Any Permission
	}{
		Any: "roles.update.any",
	},
}

var Securities = struct {
	Manage struct {
		Catalog Permission
	}
	Read struct {
		HoldingsAll Permission
		HoldingsOwn Permission
	}
	Trade struct {
		Any Permission
	}
}{
	Manage: struct {
		Catalog Permission
	}{
		Catalog: "securities.manage.catalog",
	},
	Read: struct {
		HoldingsAll Permission
		HoldingsOwn Permission
	}{
		HoldingsAll: "securities.read.holdings_all",
		HoldingsOwn: "securities.read.holdings_own",
	},
	Trade: struct {
		Any Permission
	}{
		Any: "securities.trade.any",
	},
}

var Verification = struct {
	Manage struct {
		Any Permission
	}
	Skip struct {
		Any Permission
	}
}{
	Manage: struct {
		Any Permission
	}{
		Any: "verification.manage.any",
	},
	Skip: struct {
		Any Permission
	}{
		Any: "verification.skip.any",
	},
}

var DefaultRoles = map[string][]Permission{
	"EmployeeAdmin": {
		"accounts.create.current",
		"accounts.create.foreign",
		"accounts.deactivate.any",
		"accounts.read.all",
		"accounts.read.own",
		"accounts.update.limits",
		"accounts.update.name",
		"actuaries.manage.any",
		"actuaries.read.all",
		"admin.audit.view",
		"admin.crons.manage",
		"admin.crons.trigger",
		"admin.crons.view",
		"bank_accounts.manage.any",
		"cards.approve.physical",
		"cards.approve.virtual",
		"cards.block.any",
		"cards.create.physical",
		"cards.create.virtual",
		"cards.read.all",
		"cards.read.own",
		"cards.unblock.any",
		"clients.create.any",
		"clients.read.all",
		"clients.read.assigned",
		"clients.read.own",
		"clients.update.contact",
		"clients.update.limits",
		"clients.update.profile",
		"credits.approve.cash",
		"credits.approve.housing",
		"credits.disburse.any",
		"credits.read.all",
		"credits.read.own",
		"employees.create.any",
		"employees.deactivate.any",
		"employees.permissions.assign",
		"employees.read.all",
		"employees.roles.assign",
		"employees.update.any",
		"exchange_rates.read.any",
		"exchange_rates.update.any",
		"fees.create.any",
		"fees.update.any",
		"funds.invest.on_behalf_bank",
		"funds.invest.on_behalf_client",
		"funds.invest.own",
		"funds.manage.catalog",
		"funds.read.all",
		"funds.redeem.own",
		"limit_templates.create.any",
		"limit_templates.update.any",
		"limits.employee.read",
		"limits.employee.update",
		"notifications.templates.manage",
		"orders.cancel.all",
		"orders.cancel.own",
		"orders.place.on_behalf_bank",
		"orders.place.on_behalf_client",
		"orders.place.own",
		"orders.read.all",
		"orders.read.own",
		"otc.read.all",
		"otc.trade.accept",
		"otc.trade.exercise",
		"otc.trade.expire",
		"otc.trade.on_behalf",
		"peer_banks.manage.any",
		"portfolio.view.client",
		"portfolio.view.fund",
		"roles.permissions.assign",
		"roles.permissions.revoke",
		"roles.read.all",
		"roles.update.any",
		"securities.manage.catalog",
		"securities.read.holdings_all",
		"securities.read.holdings_own",
		"securities.trade.any",
		"verification.manage.any",
		"verification.skip.any",
	},
	"EmployeeAgent": {
		"accounts.create.current",
		"accounts.create.foreign",
		"accounts.read.own",
		"cards.block.any",
		"cards.create.physical",
		"cards.create.virtual",
		"cards.read.own",
		"cards.unblock.any",
		"clients.create.any",
		"clients.read.assigned",
		"clients.update.contact",
		"clients.update.profile",
		"funds.invest.on_behalf_client",
		"funds.invest.own",
		"funds.redeem.own",
		"orders.place.on_behalf_client",
		"orders.place.own",
		"orders.read.own",
		"otc.trade.accept",
		"otc.trade.exercise",
		"otc.trade.on_behalf",
		"securities.read.holdings_own",
		"securities.trade.any",
	},
	"EmployeeBasic": {
		"accounts.read.own",
		"cards.block.any",
		"cards.create.virtual",
		"cards.read.own",
		"cards.unblock.any",
		"clients.read.assigned",
		"orders.read.own",
	},
	"EmployeeSupervisor": {
		"accounts.create.current",
		"accounts.create.foreign",
		"accounts.deactivate.any",
		"accounts.read.all",
		"accounts.read.own",
		"accounts.update.limits",
		"accounts.update.name",
		"actuaries.manage.any",
		"actuaries.read.all",
		"bank_accounts.manage.any",
		"cards.approve.physical",
		"cards.approve.virtual",
		"cards.block.any",
		"cards.create.physical",
		"cards.create.virtual",
		"cards.read.all",
		"cards.read.own",
		"cards.unblock.any",
		"clients.create.any",
		"clients.read.all",
		"clients.read.assigned",
		"clients.update.contact",
		"clients.update.limits",
		"clients.update.profile",
		"credits.approve.cash",
		"credits.approve.housing",
		"credits.disburse.any",
		"credits.read.all",
		"funds.invest.on_behalf_bank",
		"funds.invest.on_behalf_client",
		"funds.invest.own",
		"funds.manage.catalog",
		"funds.read.all",
		"funds.redeem.own",
		"orders.cancel.all",
		"orders.place.on_behalf_bank",
		"orders.place.on_behalf_client",
		"orders.place.own",
		"orders.read.all",
		"orders.read.own",
		"otc.read.all",
		"otc.trade.accept",
		"otc.trade.exercise",
		"otc.trade.expire",
		"otc.trade.on_behalf",
		"portfolio.view.client",
		"portfolio.view.fund",
		"securities.manage.catalog",
		"securities.read.holdings_all",
		"securities.read.holdings_own",
		"securities.trade.any",
		"verification.manage.any",
		"verification.skip.any",
	},
}

var catalogSet = func() map[Permission]struct{} {
	m := make(map[Permission]struct{}, len(Catalog))
	for _, p := range Catalog {
		m[p] = struct{}{}
	}
	return m
}()

// IsValid reports whether p is part of the generated catalog.
func IsValid(p Permission) bool {
	_, ok := catalogSet[p]
	return ok
}
