// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: card/card.proto

package cardpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CardService_CreateCard_FullMethodName             = "/card.CardService/CreateCard"
	CardService_GetCard_FullMethodName                = "/card.CardService/GetCard"
	CardService_ListCardsByAccount_FullMethodName     = "/card.CardService/ListCardsByAccount"
	CardService_ListCardsByClient_FullMethodName      = "/card.CardService/ListCardsByClient"
	CardService_BlockCard_FullMethodName              = "/card.CardService/BlockCard"
	CardService_UnblockCard_FullMethodName            = "/card.CardService/UnblockCard"
	CardService_DeactivateCard_FullMethodName         = "/card.CardService/DeactivateCard"
	CardService_CreateAuthorizedPerson_FullMethodName = "/card.CardService/CreateAuthorizedPerson"
	CardService_GetAuthorizedPerson_FullMethodName    = "/card.CardService/GetAuthorizedPerson"
	CardService_ListChangelog_FullMethodName          = "/card.CardService/ListChangelog"
	CardService_ListAllChangelogs_FullMethodName      = "/card.CardService/ListAllChangelogs"
)

// CardServiceClient is the client API for CardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CardServiceClient interface {
	CreateCard(ctx context.Context, in *CreateCardRequest, opts ...grpc.CallOption) (*CardResponse, error)
	GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*CardResponse, error)
	ListCardsByAccount(ctx context.Context, in *ListCardsByAccountRequest, opts ...grpc.CallOption) (*ListCardsResponse, error)
	ListCardsByClient(ctx context.Context, in *ListCardsByClientRequest, opts ...grpc.CallOption) (*ListCardsResponse, error)
	BlockCard(ctx context.Context, in *BlockCardRequest, opts ...grpc.CallOption) (*CardResponse, error)
	UnblockCard(ctx context.Context, in *UnblockCardRequest, opts ...grpc.CallOption) (*CardResponse, error)
	DeactivateCard(ctx context.Context, in *DeactivateCardRequest, opts ...grpc.CallOption) (*CardResponse, error)
	CreateAuthorizedPerson(ctx context.Context, in *CreateAuthorizedPersonRequest, opts ...grpc.CallOption) (*AuthorizedPersonResponse, error)
	GetAuthorizedPerson(ctx context.Context, in *GetAuthorizedPersonRequest, opts ...grpc.CallOption) (*AuthorizedPersonResponse, error)
	// Audit-trail reads. Returns changelog rows scoped by entity_type +
	// entity_id; pagination matches list endpoints (1-based page).
	ListChangelog(ctx context.Context, in *ListChangelogRequest, opts ...grpc.CallOption) (*ListChangelogResponse, error)
	// ListAllChangelogs returns every changelog row for this service (global
	// audit view, admin-only). Supports optional filters: since/until (unix
	// seconds), actor_id (changed_by), action string, and pagination.
	ListAllChangelogs(ctx context.Context, in *ListAllChangelogsRequest, opts ...grpc.CallOption) (*ListAllChangelogsResponse, error)
}

type cardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCardServiceClient(cc grpc.ClientConnInterface) CardServiceClient {
	return &cardServiceClient{cc}
}

func (c *cardServiceClient) CreateCard(ctx context.Context, in *CreateCardRequest, opts ...grpc.CallOption) (*CardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardResponse)
	err := c.cc.Invoke(ctx, CardService_CreateCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*CardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardResponse)
	err := c.cc.Invoke(ctx, CardService_GetCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) ListCardsByAccount(ctx context.Context, in *ListCardsByAccountRequest, opts ...grpc.CallOption) (*ListCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCardsResponse)
	err := c.cc.Invoke(ctx, CardService_ListCardsByAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) ListCardsByClient(ctx context.Context, in *ListCardsByClientRequest, opts ...grpc.CallOption) (*ListCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCardsResponse)
	err := c.cc.Invoke(ctx, CardService_ListCardsByClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) BlockCard(ctx context.Context, in *BlockCardRequest, opts ...grpc.CallOption) (*CardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardResponse)
	err := c.cc.Invoke(ctx, CardService_BlockCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) UnblockCard(ctx context.Context, in *UnblockCardRequest, opts ...grpc.CallOption) (*CardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardResponse)
	err := c.cc.Invoke(ctx, CardService_UnblockCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) DeactivateCard(ctx context.Context, in *DeactivateCardRequest, opts ...grpc.CallOption) (*CardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardResponse)
	err := c.cc.Invoke(ctx, CardService_DeactivateCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) CreateAuthorizedPerson(ctx context.Context, in *CreateAuthorizedPersonRequest, opts ...grpc.CallOption) (*AuthorizedPersonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizedPersonResponse)
	err := c.cc.Invoke(ctx, CardService_CreateAuthorizedPerson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) GetAuthorizedPerson(ctx context.Context, in *GetAuthorizedPersonRequest, opts ...grpc.CallOption) (*AuthorizedPersonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizedPersonResponse)
	err := c.cc.Invoke(ctx, CardService_GetAuthorizedPerson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) ListChangelog(ctx context.Context, in *ListChangelogRequest, opts ...grpc.CallOption) (*ListChangelogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChangelogResponse)
	err := c.cc.Invoke(ctx, CardService_ListChangelog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) ListAllChangelogs(ctx context.Context, in *ListAllChangelogsRequest, opts ...grpc.CallOption) (*ListAllChangelogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllChangelogsResponse)
	err := c.cc.Invoke(ctx, CardService_ListAllChangelogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardServiceServer is the server API for CardService service.
// All implementations must embed UnimplementedCardServiceServer
// for forward compatibility.
type CardServiceServer interface {
	CreateCard(context.Context, *CreateCardRequest) (*CardResponse, error)
	GetCard(context.Context, *GetCardRequest) (*CardResponse, error)
	ListCardsByAccount(context.Context, *ListCardsByAccountRequest) (*ListCardsResponse, error)
	ListCardsByClient(context.Context, *ListCardsByClientRequest) (*ListCardsResponse, error)
	BlockCard(context.Context, *BlockCardRequest) (*CardResponse, error)
	UnblockCard(context.Context, *UnblockCardRequest) (*CardResponse, error)
	DeactivateCard(context.Context, *DeactivateCardRequest) (*CardResponse, error)
	CreateAuthorizedPerson(context.Context, *CreateAuthorizedPersonRequest) (*AuthorizedPersonResponse, error)
	GetAuthorizedPerson(context.Context, *GetAuthorizedPersonRequest) (*AuthorizedPersonResponse, error)
	// Audit-trail reads. Returns changelog rows scoped by entity_type +
	// entity_id; pagination matches list endpoints (1-based page).
	ListChangelog(context.Context, *ListChangelogRequest) (*ListChangelogResponse, error)
	// ListAllChangelogs returns every changelog row for this service (global
	// audit view, admin-only). Supports optional filters: since/until (unix
	// seconds), actor_id (changed_by), action string, and pagination.
	ListAllChangelogs(context.Context, *ListAllChangelogsRequest) (*ListAllChangelogsResponse, error)
	mustEmbedUnimplementedCardServiceServer()
}

// UnimplementedCardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCardServiceServer struct{}

func (UnimplementedCardServiceServer) CreateCard(context.Context, *CreateCardRequest) (*CardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCard not implemented")
}
func (UnimplementedCardServiceServer) GetCard(context.Context, *GetCardRequest) (*CardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCard not implemented")
}
func (UnimplementedCardServiceServer) ListCardsByAccount(context.Context, *ListCardsByAccountRequest) (*ListCardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCardsByAccount not implemented")
}
func (UnimplementedCardServiceServer) ListCardsByClient(context.Context, *ListCardsByClientRequest) (*ListCardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCardsByClient not implemented")
}
func (UnimplementedCardServiceServer) BlockCard(context.Context, *BlockCardRequest) (*CardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BlockCard not implemented")
}
func (UnimplementedCardServiceServer) UnblockCard(context.Context, *UnblockCardRequest) (*CardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnblockCard not implemented")
}
func (UnimplementedCardServiceServer) DeactivateCard(context.Context, *DeactivateCardRequest) (*CardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateCard not implemented")
}
func (UnimplementedCardServiceServer) CreateAuthorizedPerson(context.Context, *CreateAuthorizedPersonRequest) (*AuthorizedPersonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAuthorizedPerson not implemented")
}
func (UnimplementedCardServiceServer) GetAuthorizedPerson(context.Context, *GetAuthorizedPersonRequest) (*AuthorizedPersonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthorizedPerson not implemented")
}
func (UnimplementedCardServiceServer) ListChangelog(context.Context, *ListChangelogRequest) (*ListChangelogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChangelog not implemented")
}
func (UnimplementedCardServiceServer) ListAllChangelogs(context.Context, *ListAllChangelogsRequest) (*ListAllChangelogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllChangelogs not implemented")
}
func (UnimplementedCardServiceServer) mustEmbedUnimplementedCardServiceServer() {}
func (UnimplementedCardServiceServer) testEmbeddedByValue()                     {}

// UnsafeCardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CardServiceServer will
// result in compilation errors.
type UnsafeCardServiceServer interface {
	mustEmbedUnimplementedCardServiceServer()
}

func RegisterCardServiceServer(s grpc.ServiceRegistrar, srv CardServiceServer) {
	// If the following call panics, it indicates UnimplementedCardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CardService_ServiceDesc, srv)
}

func _CardService_CreateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).CreateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_CreateCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).CreateCard(ctx, req.(*CreateCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_GetCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).GetCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_GetCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).GetCard(ctx, req.(*GetCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_ListCardsByAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCardsByAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).ListCardsByAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_ListCardsByAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).ListCardsByAccount(ctx, req.(*ListCardsByAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_ListCardsByClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCardsByClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).ListCardsByClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_ListCardsByClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).ListCardsByClient(ctx, req.(*ListCardsByClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_BlockCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).BlockCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_BlockCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).BlockCard(ctx, req.(*BlockCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_UnblockCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).UnblockCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_UnblockCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).UnblockCard(ctx, req.(*UnblockCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_DeactivateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).DeactivateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_DeactivateCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).DeactivateCard(ctx, req.(*DeactivateCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_CreateAuthorizedPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthorizedPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).CreateAuthorizedPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_CreateAuthorizedPerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).CreateAuthorizedPerson(ctx, req.(*CreateAuthorizedPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_GetAuthorizedPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorizedPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).GetAuthorizedPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_GetAuthorizedPerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).GetAuthorizedPerson(ctx, req.(*GetAuthorizedPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_ListChangelog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChangelogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).ListChangelog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_ListChangelog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).ListChangelog(ctx, req.(*ListChangelogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_ListAllChangelogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllChangelogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).ListAllChangelogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_ListAllChangelogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).ListAllChangelogs(ctx, req.(*ListAllChangelogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CardService_ServiceDesc is the grpc.ServiceDesc for CardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "card.CardService",
	HandlerType: (*CardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCard",
			Handler:    _CardService_CreateCard_Handler,
		},
		{
			MethodName: "GetCard",
			Handler:    _CardService_GetCard_Handler,
		},
		{
			MethodName: "ListCardsByAccount",
			Handler:    _CardService_ListCardsByAccount_Handler,
		},
		{
			MethodName: "ListCardsByClient",
			Handler:    _CardService_ListCardsByClient_Handler,
		},
		{
			MethodName: "BlockCard",
			Handler:    _CardService_BlockCard_Handler,
		},
		{
			MethodName: "UnblockCard",
			Handler:    _CardService_UnblockCard_Handler,
		},
		{
			MethodName: "DeactivateCard",
			Handler:    _CardService_DeactivateCard_Handler,
		},
		{
			MethodName: "CreateAuthorizedPerson",
			Handler:    _CardService_CreateAuthorizedPerson_Handler,
		},
		{
			MethodName: "GetAuthorizedPerson",
			Handler:    _CardService_GetAuthorizedPerson_Handler,
		},
		{
			MethodName: "ListChangelog",
			Handler:    _CardService_ListChangelog_Handler,
		},
		{
			MethodName: "ListAllChangelogs",
			Handler:    _CardService_ListAllChangelogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "card/card.proto",
}

const (
	VirtualCardService_CreateVirtualCard_FullMethodName  = "/card.VirtualCardService/CreateVirtualCard"
	VirtualCardService_SetCardPin_FullMethodName         = "/card.VirtualCardService/SetCardPin"
	VirtualCardService_VerifyCardPin_FullMethodName      = "/card.VirtualCardService/VerifyCardPin"
	VirtualCardService_TemporaryBlockCard_FullMethodName = "/card.VirtualCardService/TemporaryBlockCard"
	VirtualCardService_UseCard_FullMethodName            = "/card.VirtualCardService/UseCard"
)

// VirtualCardServiceClient is the client API for VirtualCardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VirtualCardServiceClient interface {
	CreateVirtualCard(ctx context.Context, in *CreateVirtualCardRequest, opts ...grpc.CallOption) (*CardResponse, error)
	SetCardPin(ctx context.Context, in *SetCardPinRequest, opts ...grpc.CallOption) (*SetCardPinResponse, error)
	VerifyCardPin(ctx context.Context, in *VerifyCardPinRequest, opts ...grpc.CallOption) (*VerifyCardPinResponse, error)
	TemporaryBlockCard(ctx context.Context, in *TemporaryBlockCardRequest, opts ...grpc.CallOption) (*CardResponse, error)
	UseCard(ctx context.Context, in *UseCardRequest, opts ...grpc.CallOption) (*UseCardResponse, error)
}

type virtualCardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVirtualCardServiceClient(cc grpc.ClientConnInterface) VirtualCardServiceClient {
	return &virtualCardServiceClient{cc}
}

func (c *virtualCardServiceClient) CreateVirtualCard(ctx context.Context, in *CreateVirtualCardRequest, opts ...grpc.CallOption) (*CardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardResponse)
	err := c.cc.Invoke(ctx, VirtualCardService_CreateVirtualCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualCardServiceClient) SetCardPin(ctx context.Context, in *SetCardPinRequest, opts ...grpc.CallOption) (*SetCardPinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCardPinResponse)
	err := c.cc.Invoke(ctx, VirtualCardService_SetCardPin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualCardServiceClient) VerifyCardPin(ctx context.Context, in *VerifyCardPinRequest, opts ...grpc.CallOption) (*VerifyCardPinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyCardPinResponse)
	err := c.cc.Invoke(ctx, VirtualCardService_VerifyCardPin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualCardServiceClient) TemporaryBlockCard(ctx context.Context, in *TemporaryBlockCardRequest, opts ...grpc.CallOption) (*CardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardResponse)
	err := c.cc.Invoke(ctx, VirtualCardService_TemporaryBlockCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualCardServiceClient) UseCard(ctx context.Context, in *UseCardRequest, opts ...grpc.CallOption) (*UseCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UseCardResponse)
	err := c.cc.Invoke(ctx, VirtualCardService_UseCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualCardServiceServer is the server API for VirtualCardService service.
// All implementations must embed UnimplementedVirtualCardServiceServer
// for forward compatibility.
type VirtualCardServiceServer interface {
	CreateVirtualCard(context.Context, *CreateVirtualCardRequest) (*CardResponse, error)
	SetCardPin(context.Context, *SetCardPinRequest) (*SetCardPinResponse, error)
	VerifyCardPin(context.Context, *VerifyCardPinRequest) (*VerifyCardPinResponse, error)
	TemporaryBlockCard(context.Context, *TemporaryBlockCardRequest) (*CardResponse, error)
	UseCard(context.Context, *UseCardRequest) (*UseCardResponse, error)
	mustEmbedUnimplementedVirtualCardServiceServer()
}

// UnimplementedVirtualCardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVirtualCardServiceServer struct{}

func (UnimplementedVirtualCardServiceServer) CreateVirtualCard(context.Context, *CreateVirtualCardRequest) (*CardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVirtualCard not implemented")
}
func (UnimplementedVirtualCardServiceServer) SetCardPin(context.Context, *SetCardPinRequest) (*SetCardPinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCardPin not implemented")
}
func (UnimplementedVirtualCardServiceServer) VerifyCardPin(context.Context, *VerifyCardPinRequest) (*VerifyCardPinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyCardPin not implemented")
}
func (UnimplementedVirtualCardServiceServer) TemporaryBlockCard(context.Context, *TemporaryBlockCardRequest) (*CardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TemporaryBlockCard not implemented")
}
func (UnimplementedVirtualCardServiceServer) UseCard(context.Context, *UseCardRequest) (*UseCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UseCard not implemented")
}
func (UnimplementedVirtualCardServiceServer) mustEmbedUnimplementedVirtualCardServiceServer() {}
func (UnimplementedVirtualCardServiceServer) testEmbeddedByValue()                            {}

// UnsafeVirtualCardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VirtualCardServiceServer will
// result in compilation errors.
type UnsafeVirtualCardServiceServer interface {
	mustEmbedUnimplementedVirtualCardServiceServer()
}

func RegisterVirtualCardServiceServer(s grpc.ServiceRegistrar, srv VirtualCardServiceServer) {
	// If the following call panics, it indicates UnimplementedVirtualCardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VirtualCardService_ServiceDesc, srv)
}

func _VirtualCardService_CreateVirtualCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVirtualCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualCardServiceServer).CreateVirtualCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualCardService_CreateVirtualCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualCardServiceServer).CreateVirtualCard(ctx, req.(*CreateVirtualCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualCardService_SetCardPin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCardPinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualCardServiceServer).SetCardPin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualCardService_SetCardPin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualCardServiceServer).SetCardPin(ctx, req.(*SetCardPinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualCardService_VerifyCardPin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCardPinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualCardServiceServer).VerifyCardPin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualCardService_VerifyCardPin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualCardServiceServer).VerifyCardPin(ctx, req.(*VerifyCardPinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualCardService_TemporaryBlockCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemporaryBlockCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualCardServiceServer).TemporaryBlockCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualCardService_TemporaryBlockCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualCardServiceServer).TemporaryBlockCard(ctx, req.(*TemporaryBlockCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualCardService_UseCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualCardServiceServer).UseCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualCardService_UseCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualCardServiceServer).UseCard(ctx, req.(*UseCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VirtualCardService_ServiceDesc is the grpc.ServiceDesc for VirtualCardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VirtualCardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "card.VirtualCardService",
	HandlerType: (*VirtualCardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVirtualCard",
			Handler:    _VirtualCardService_CreateVirtualCard_Handler,
		},
		{
			MethodName: "SetCardPin",
			Handler:    _VirtualCardService_SetCardPin_Handler,
		},
		{
			MethodName: "VerifyCardPin",
			Handler:    _VirtualCardService_VerifyCardPin_Handler,
		},
		{
			MethodName: "TemporaryBlockCard",
			Handler:    _VirtualCardService_TemporaryBlockCard_Handler,
		},
		{
			MethodName: "UseCard",
			Handler:    _VirtualCardService_UseCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "card/card.proto",
}

const (
	CardRequestService_CreateCardRequest_FullMethodName        = "/card.CardRequestService/CreateCardRequest"
	CardRequestService_GetCardRequest_FullMethodName           = "/card.CardRequestService/GetCardRequest"
	CardRequestService_ListCardRequests_FullMethodName         = "/card.CardRequestService/ListCardRequests"
	CardRequestService_ListCardRequestsByClient_FullMethodName = "/card.CardRequestService/ListCardRequestsByClient"
	CardRequestService_ApproveCardRequest_FullMethodName       = "/card.CardRequestService/ApproveCardRequest"
	CardRequestService_RejectCardRequest_FullMethodName        = "/card.CardRequestService/RejectCardRequest"
)

// CardRequestServiceClient is the client API for CardRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CardRequestServiceClient interface {
	CreateCardRequest(ctx context.Context, in *CreateCardRequestRequest, opts ...grpc.CallOption) (*CardRequestResponse, error)
	GetCardRequest(ctx context.Context, in *GetCardRequestRequest, opts ...grpc.CallOption) (*CardRequestResponse, error)
	ListCardRequests(ctx context.Context, in *ListCardRequestsRequest, opts ...grpc.CallOption) (*ListCardRequestsResponse, error)
	ListCardRequestsByClient(ctx context.Context, in *ListCardRequestsByClientRequest, opts ...grpc.CallOption) (*ListCardRequestsResponse, error)
	ApproveCardRequest(ctx context.Context, in *ApproveCardRequestRequest, opts ...grpc.CallOption) (*CardRequestApprovedResponse, error)
	RejectCardRequest(ctx context.Context, in *RejectCardRequestRequest, opts ...grpc.CallOption) (*CardRequestResponse, error)
}

type cardRequestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCardRequestServiceClient(cc grpc.ClientConnInterface) CardRequestServiceClient {
	return &cardRequestServiceClient{cc}
}

func (c *cardRequestServiceClient) CreateCardRequest(ctx context.Context, in *CreateCardRequestRequest, opts ...grpc.CallOption) (*CardRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardRequestResponse)
	err := c.cc.Invoke(ctx, CardRequestService_CreateCardRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardRequestServiceClient) GetCardRequest(ctx context.Context, in *GetCardRequestRequest, opts ...grpc.CallOption) (*CardRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardRequestResponse)
	err := c.cc.Invoke(ctx, CardRequestService_GetCardRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardRequestServiceClient) ListCardRequests(ctx context.Context, in *ListCardRequestsRequest, opts ...grpc.CallOption) (*ListCardRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCardRequestsResponse)
	err := c.cc.Invoke(ctx, CardRequestService_ListCardRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardRequestServiceClient) ListCardRequestsByClient(ctx context.Context, in *ListCardRequestsByClientRequest, opts ...grpc.CallOption) (*ListCardRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCardRequestsResponse)
	err := c.cc.Invoke(ctx, CardRequestService_ListCardRequestsByClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardRequestServiceClient) ApproveCardRequest(ctx context.Context, in *ApproveCardRequestRequest, opts ...grpc.CallOption) (*CardRequestApprovedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardRequestApprovedResponse)
	err := c.cc.Invoke(ctx, CardRequestService_ApproveCardRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardRequestServiceClient) RejectCardRequest(ctx context.Context, in *RejectCardRequestRequest, opts ...grpc.CallOption) (*CardRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardRequestResponse)
	err := c.cc.Invoke(ctx, CardRequestService_RejectCardRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardRequestServiceServer is the server API for CardRequestService service.
// All implementations must embed UnimplementedCardRequestServiceServer
// for forward compatibility.
type CardRequestServiceServer interface {
	CreateCardRequest(context.Context, *CreateCardRequestRequest) (*CardRequestResponse, error)
	GetCardRequest(context.Context, *GetCardRequestRequest) (*CardRequestResponse, error)
	ListCardRequests(context.Context, *ListCardRequestsRequest) (*ListCardRequestsResponse, error)
	ListCardRequestsByClient(context.Context, *ListCardRequestsByClientRequest) (*ListCardRequestsResponse, error)
	ApproveCardRequest(context.Context, *ApproveCardRequestRequest) (*CardRequestApprovedResponse, error)
	RejectCardRequest(context.Context, *RejectCardRequestRequest) (*CardRequestResponse, error)
	mustEmbedUnimplementedCardRequestServiceServer()
}

// UnimplementedCardRequestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCardRequestServiceServer struct{}

func (UnimplementedCardRequestServiceServer) CreateCardRequest(context.Context, *CreateCardRequestRequest) (*CardRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCardRequest not implemented")
}
func (UnimplementedCardRequestServiceServer) GetCardRequest(context.Context, *GetCardRequestRequest) (*CardRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCardRequest not implemented")
}
func (UnimplementedCardRequestServiceServer) ListCardRequests(context.Context, *ListCardRequestsRequest) (*ListCardRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCardRequests not implemented")
}
func (UnimplementedCardRequestServiceServer) ListCardRequestsByClient(context.Context, *ListCardRequestsByClientRequest) (*ListCardRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCardRequestsByClient not implemented")
}
func (UnimplementedCardRequestServiceServer) ApproveCardRequest(context.Context, *ApproveCardRequestRequest) (*CardRequestApprovedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveCardRequest not implemented")
}
func (UnimplementedCardRequestServiceServer) RejectCardRequest(context.Context, *RejectCardRequestRequest) (*CardRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectCardRequest not implemented")
}
func (UnimplementedCardRequestServiceServer) mustEmbedUnimplementedCardRequestServiceServer() {}
func (UnimplementedCardRequestServiceServer) testEmbeddedByValue()                            {}

// UnsafeCardRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CardRequestServiceServer will
// result in compilation errors.
type UnsafeCardRequestServiceServer interface {
	mustEmbedUnimplementedCardRequestServiceServer()
}

func RegisterCardRequestServiceServer(s grpc.ServiceRegistrar, srv CardRequestServiceServer) {
	// If the following call panics, it indicates UnimplementedCardRequestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CardRequestService_ServiceDesc, srv)
}

func _CardRequestService_CreateCardRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCardRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardRequestServiceServer).CreateCardRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardRequestService_CreateCardRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardRequestServiceServer).CreateCardRequest(ctx, req.(*CreateCardRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardRequestService_GetCardRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardRequestServiceServer).GetCardRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardRequestService_GetCardRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardRequestServiceServer).GetCardRequest(ctx, req.(*GetCardRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardRequestService_ListCardRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCardRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardRequestServiceServer).ListCardRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardRequestService_ListCardRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardRequestServiceServer).ListCardRequests(ctx, req.(*ListCardRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardRequestService_ListCardRequestsByClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCardRequestsByClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardRequestServiceServer).ListCardRequestsByClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardRequestService_ListCardRequestsByClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardRequestServiceServer).ListCardRequestsByClient(ctx, req.(*ListCardRequestsByClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardRequestService_ApproveCardRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveCardRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardRequestServiceServer).ApproveCardRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardRequestService_ApproveCardRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardRequestServiceServer).ApproveCardRequest(ctx, req.(*ApproveCardRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardRequestService_RejectCardRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectCardRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardRequestServiceServer).RejectCardRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardRequestService_RejectCardRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardRequestServiceServer).RejectCardRequest(ctx, req.(*RejectCardRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CardRequestService_ServiceDesc is the grpc.ServiceDesc for CardRequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CardRequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "card.CardRequestService",
	HandlerType: (*CardRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCardRequest",
			Handler:    _CardRequestService_CreateCardRequest_Handler,
		},
		{
			MethodName: "GetCardRequest",
			Handler:    _CardRequestService_GetCardRequest_Handler,
		},
		{
			MethodName: "ListCardRequests",
			Handler:    _CardRequestService_ListCardRequests_Handler,
		},
		{
			MethodName: "ListCardRequestsByClient",
			Handler:    _CardRequestService_ListCardRequestsByClient_Handler,
		},
		{
			MethodName: "ApproveCardRequest",
			Handler:    _CardRequestService_ApproveCardRequest_Handler,
		},
		{
			MethodName: "RejectCardRequest",
			Handler:    _CardRequestService_RejectCardRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "card/card.proto",
}
