// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: transaction/transaction.proto

package transactionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionService_CreatePayment_FullMethodName          = "/transaction.TransactionService/CreatePayment"
	TransactionService_ExecutePayment_FullMethodName         = "/transaction.TransactionService/ExecutePayment"
	TransactionService_GetPayment_FullMethodName             = "/transaction.TransactionService/GetPayment"
	TransactionService_ListPaymentsByAccount_FullMethodName  = "/transaction.TransactionService/ListPaymentsByAccount"
	TransactionService_ListPaymentsByClient_FullMethodName   = "/transaction.TransactionService/ListPaymentsByClient"
	TransactionService_CreateTransfer_FullMethodName         = "/transaction.TransactionService/CreateTransfer"
	TransactionService_ExecuteTransfer_FullMethodName        = "/transaction.TransactionService/ExecuteTransfer"
	TransactionService_GetTransfer_FullMethodName            = "/transaction.TransactionService/GetTransfer"
	TransactionService_GetTransferStatus_FullMethodName      = "/transaction.TransactionService/GetTransferStatus"
	TransactionService_ListTransfersByClient_FullMethodName  = "/transaction.TransactionService/ListTransfersByClient"
	TransactionService_CreatePaymentRecipient_FullMethodName = "/transaction.TransactionService/CreatePaymentRecipient"
	TransactionService_GetPaymentRecipient_FullMethodName    = "/transaction.TransactionService/GetPaymentRecipient"
	TransactionService_ListPaymentRecipients_FullMethodName  = "/transaction.TransactionService/ListPaymentRecipients"
	TransactionService_UpdatePaymentRecipient_FullMethodName = "/transaction.TransactionService/UpdatePaymentRecipient"
	TransactionService_DeletePaymentRecipient_FullMethodName = "/transaction.TransactionService/DeletePaymentRecipient"
)

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionServiceClient interface {
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	ExecutePayment(ctx context.Context, in *ExecutePaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	ListPaymentsByAccount(ctx context.Context, in *ListPaymentsByAccountRequest, opts ...grpc.CallOption) (*ListPaymentsResponse, error)
	ListPaymentsByClient(ctx context.Context, in *ListPaymentsByClientRequest, opts ...grpc.CallOption) (*ListPaymentsResponse, error)
	CreateTransfer(ctx context.Context, in *CreateTransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	ExecuteTransfer(ctx context.Context, in *ExecuteTransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	GetTransfer(ctx context.Context, in *GetTransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	GetTransferStatus(ctx context.Context, in *GetTransferRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error)
	ListTransfersByClient(ctx context.Context, in *ListTransfersByClientRequest, opts ...grpc.CallOption) (*ListTransfersResponse, error)
	CreatePaymentRecipient(ctx context.Context, in *CreatePaymentRecipientRequest, opts ...grpc.CallOption) (*PaymentRecipientResponse, error)
	GetPaymentRecipient(ctx context.Context, in *GetPaymentRecipientRequest, opts ...grpc.CallOption) (*PaymentRecipientResponse, error)
	ListPaymentRecipients(ctx context.Context, in *ListPaymentRecipientsRequest, opts ...grpc.CallOption) (*ListPaymentRecipientsResponse, error)
	UpdatePaymentRecipient(ctx context.Context, in *UpdatePaymentRecipientRequest, opts ...grpc.CallOption) (*PaymentRecipientResponse, error)
	DeletePaymentRecipient(ctx context.Context, in *DeletePaymentRecipientRequest, opts ...grpc.CallOption) (*DeletePaymentRecipientResponse, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, TransactionService_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ExecutePayment(ctx context.Context, in *ExecutePaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, TransactionService_ExecutePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ListPaymentsByAccount(ctx context.Context, in *ListPaymentsByAccountRequest, opts ...grpc.CallOption) (*ListPaymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymentsResponse)
	err := c.cc.Invoke(ctx, TransactionService_ListPaymentsByAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ListPaymentsByClient(ctx context.Context, in *ListPaymentsByClientRequest, opts ...grpc.CallOption) (*ListPaymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymentsResponse)
	err := c.cc.Invoke(ctx, TransactionService_ListPaymentsByClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) CreateTransfer(ctx context.Context, in *CreateTransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, TransactionService_CreateTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ExecuteTransfer(ctx context.Context, in *ExecuteTransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, TransactionService_ExecuteTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetTransfer(ctx context.Context, in *GetTransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetTransferStatus(ctx context.Context, in *GetTransferRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferStatusResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetTransferStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ListTransfersByClient(ctx context.Context, in *ListTransfersByClientRequest, opts ...grpc.CallOption) (*ListTransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransfersResponse)
	err := c.cc.Invoke(ctx, TransactionService_ListTransfersByClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) CreatePaymentRecipient(ctx context.Context, in *CreatePaymentRecipientRequest, opts ...grpc.CallOption) (*PaymentRecipientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentRecipientResponse)
	err := c.cc.Invoke(ctx, TransactionService_CreatePaymentRecipient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetPaymentRecipient(ctx context.Context, in *GetPaymentRecipientRequest, opts ...grpc.CallOption) (*PaymentRecipientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentRecipientResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetPaymentRecipient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ListPaymentRecipients(ctx context.Context, in *ListPaymentRecipientsRequest, opts ...grpc.CallOption) (*ListPaymentRecipientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymentRecipientsResponse)
	err := c.cc.Invoke(ctx, TransactionService_ListPaymentRecipients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) UpdatePaymentRecipient(ctx context.Context, in *UpdatePaymentRecipientRequest, opts ...grpc.CallOption) (*PaymentRecipientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentRecipientResponse)
	err := c.cc.Invoke(ctx, TransactionService_UpdatePaymentRecipient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) DeletePaymentRecipient(ctx context.Context, in *DeletePaymentRecipientRequest, opts ...grpc.CallOption) (*DeletePaymentRecipientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePaymentRecipientResponse)
	err := c.cc.Invoke(ctx, TransactionService_DeletePaymentRecipient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
// All implementations must embed UnimplementedTransactionServiceServer
// for forward compatibility.
type TransactionServiceServer interface {
	CreatePayment(context.Context, *CreatePaymentRequest) (*PaymentResponse, error)
	ExecutePayment(context.Context, *ExecutePaymentRequest) (*PaymentResponse, error)
	GetPayment(context.Context, *GetPaymentRequest) (*PaymentResponse, error)
	ListPaymentsByAccount(context.Context, *ListPaymentsByAccountRequest) (*ListPaymentsResponse, error)
	ListPaymentsByClient(context.Context, *ListPaymentsByClientRequest) (*ListPaymentsResponse, error)
	CreateTransfer(context.Context, *CreateTransferRequest) (*TransferResponse, error)
	ExecuteTransfer(context.Context, *ExecuteTransferRequest) (*TransferResponse, error)
	GetTransfer(context.Context, *GetTransferRequest) (*TransferResponse, error)
	GetTransferStatus(context.Context, *GetTransferRequest) (*TransferStatusResponse, error)
	ListTransfersByClient(context.Context, *ListTransfersByClientRequest) (*ListTransfersResponse, error)
	CreatePaymentRecipient(context.Context, *CreatePaymentRecipientRequest) (*PaymentRecipientResponse, error)
	GetPaymentRecipient(context.Context, *GetPaymentRecipientRequest) (*PaymentRecipientResponse, error)
	ListPaymentRecipients(context.Context, *ListPaymentRecipientsRequest) (*ListPaymentRecipientsResponse, error)
	UpdatePaymentRecipient(context.Context, *UpdatePaymentRecipientRequest) (*PaymentRecipientResponse, error)
	DeletePaymentRecipient(context.Context, *DeletePaymentRecipientRequest) (*DeletePaymentRecipientResponse, error)
	mustEmbedUnimplementedTransactionServiceServer()
}

// UnimplementedTransactionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionServiceServer struct{}

func (UnimplementedTransactionServiceServer) CreatePayment(context.Context, *CreatePaymentRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedTransactionServiceServer) ExecutePayment(context.Context, *ExecutePaymentRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePayment not implemented")
}
func (UnimplementedTransactionServiceServer) GetPayment(context.Context, *GetPaymentRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayment not implemented")
}
func (UnimplementedTransactionServiceServer) ListPaymentsByAccount(context.Context, *ListPaymentsByAccountRequest) (*ListPaymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPaymentsByAccount not implemented")
}
func (UnimplementedTransactionServiceServer) ListPaymentsByClient(context.Context, *ListPaymentsByClientRequest) (*ListPaymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPaymentsByClient not implemented")
}
func (UnimplementedTransactionServiceServer) CreateTransfer(context.Context, *CreateTransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTransfer not implemented")
}
func (UnimplementedTransactionServiceServer) ExecuteTransfer(context.Context, *ExecuteTransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTransfer not implemented")
}
func (UnimplementedTransactionServiceServer) GetTransfer(context.Context, *GetTransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransfer not implemented")
}
func (UnimplementedTransactionServiceServer) GetTransferStatus(context.Context, *GetTransferRequest) (*TransferStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransferStatus not implemented")
}
func (UnimplementedTransactionServiceServer) ListTransfersByClient(context.Context, *ListTransfersByClientRequest) (*ListTransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTransfersByClient not implemented")
}
func (UnimplementedTransactionServiceServer) CreatePaymentRecipient(context.Context, *CreatePaymentRecipientRequest) (*PaymentRecipientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePaymentRecipient not implemented")
}
func (UnimplementedTransactionServiceServer) GetPaymentRecipient(context.Context, *GetPaymentRecipientRequest) (*PaymentRecipientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentRecipient not implemented")
}
func (UnimplementedTransactionServiceServer) ListPaymentRecipients(context.Context, *ListPaymentRecipientsRequest) (*ListPaymentRecipientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPaymentRecipients not implemented")
}
func (UnimplementedTransactionServiceServer) UpdatePaymentRecipient(context.Context, *UpdatePaymentRecipientRequest) (*PaymentRecipientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePaymentRecipient not implemented")
}
func (UnimplementedTransactionServiceServer) DeletePaymentRecipient(context.Context, *DeletePaymentRecipientRequest) (*DeletePaymentRecipientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePaymentRecipient not implemented")
}
func (UnimplementedTransactionServiceServer) mustEmbedUnimplementedTransactionServiceServer() {}
func (UnimplementedTransactionServiceServer) testEmbeddedByValue()                            {}

// UnsafeTransactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionServiceServer will
// result in compilation errors.
type UnsafeTransactionServiceServer interface {
	mustEmbedUnimplementedTransactionServiceServer()
}

func RegisterTransactionServiceServer(s grpc.ServiceRegistrar, srv TransactionServiceServer) {
	// If the following call panics, it indicates UnimplementedTransactionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionService_ServiceDesc, srv)
}

func _TransactionService_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ExecutePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ExecutePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ExecutePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ExecutePayment(ctx, req.(*ExecutePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetPayment(ctx, req.(*GetPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ListPaymentsByAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymentsByAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ListPaymentsByAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ListPaymentsByAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ListPaymentsByAccount(ctx, req.(*ListPaymentsByAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ListPaymentsByClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymentsByClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ListPaymentsByClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ListPaymentsByClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ListPaymentsByClient(ctx, req.(*ListPaymentsByClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_CreateTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CreateTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_CreateTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CreateTransfer(ctx, req.(*CreateTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ExecuteTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ExecuteTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ExecuteTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ExecuteTransfer(ctx, req.(*ExecuteTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetTransfer(ctx, req.(*GetTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetTransferStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetTransferStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetTransferStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetTransferStatus(ctx, req.(*GetTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ListTransfersByClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransfersByClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ListTransfersByClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ListTransfersByClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ListTransfersByClient(ctx, req.(*ListTransfersByClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_CreatePaymentRecipient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRecipientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CreatePaymentRecipient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_CreatePaymentRecipient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CreatePaymentRecipient(ctx, req.(*CreatePaymentRecipientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetPaymentRecipient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentRecipientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetPaymentRecipient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetPaymentRecipient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetPaymentRecipient(ctx, req.(*GetPaymentRecipientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ListPaymentRecipients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymentRecipientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ListPaymentRecipients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ListPaymentRecipients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ListPaymentRecipients(ctx, req.(*ListPaymentRecipientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_UpdatePaymentRecipient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaymentRecipientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).UpdatePaymentRecipient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_UpdatePaymentRecipient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).UpdatePaymentRecipient(ctx, req.(*UpdatePaymentRecipientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_DeletePaymentRecipient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePaymentRecipientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).DeletePaymentRecipient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_DeletePaymentRecipient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).DeletePaymentRecipient(ctx, req.(*DeletePaymentRecipientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionService_ServiceDesc is the grpc.ServiceDesc for TransactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePayment",
			Handler:    _TransactionService_CreatePayment_Handler,
		},
		{
			MethodName: "ExecutePayment",
			Handler:    _TransactionService_ExecutePayment_Handler,
		},
		{
			MethodName: "GetPayment",
			Handler:    _TransactionService_GetPayment_Handler,
		},
		{
			MethodName: "ListPaymentsByAccount",
			Handler:    _TransactionService_ListPaymentsByAccount_Handler,
		},
		{
			MethodName: "ListPaymentsByClient",
			Handler:    _TransactionService_ListPaymentsByClient_Handler,
		},
		{
			MethodName: "CreateTransfer",
			Handler:    _TransactionService_CreateTransfer_Handler,
		},
		{
			MethodName: "ExecuteTransfer",
			Handler:    _TransactionService_ExecuteTransfer_Handler,
		},
		{
			MethodName: "GetTransfer",
			Handler:    _TransactionService_GetTransfer_Handler,
		},
		{
			MethodName: "GetTransferStatus",
			Handler:    _TransactionService_GetTransferStatus_Handler,
		},
		{
			MethodName: "ListTransfersByClient",
			Handler:    _TransactionService_ListTransfersByClient_Handler,
		},
		{
			MethodName: "CreatePaymentRecipient",
			Handler:    _TransactionService_CreatePaymentRecipient_Handler,
		},
		{
			MethodName: "GetPaymentRecipient",
			Handler:    _TransactionService_GetPaymentRecipient_Handler,
		},
		{
			MethodName: "ListPaymentRecipients",
			Handler:    _TransactionService_ListPaymentRecipients_Handler,
		},
		{
			MethodName: "UpdatePaymentRecipient",
			Handler:    _TransactionService_UpdatePaymentRecipient_Handler,
		},
		{
			MethodName: "DeletePaymentRecipient",
			Handler:    _TransactionService_DeletePaymentRecipient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction/transaction.proto",
}

const (
	FeeService_ListFees_FullMethodName     = "/transaction.FeeService/ListFees"
	FeeService_CreateFee_FullMethodName    = "/transaction.FeeService/CreateFee"
	FeeService_UpdateFee_FullMethodName    = "/transaction.FeeService/UpdateFee"
	FeeService_DeleteFee_FullMethodName    = "/transaction.FeeService/DeleteFee"
	FeeService_CalculateFee_FullMethodName = "/transaction.FeeService/CalculateFee"
)

// FeeServiceClient is the client API for FeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeeServiceClient interface {
	ListFees(ctx context.Context, in *ListFeesRequest, opts ...grpc.CallOption) (*ListFeesResponse, error)
	CreateFee(ctx context.Context, in *CreateFeeRequest, opts ...grpc.CallOption) (*TransferFeeResponse, error)
	UpdateFee(ctx context.Context, in *UpdateFeeRequest, opts ...grpc.CallOption) (*TransferFeeResponse, error)
	DeleteFee(ctx context.Context, in *DeleteFeeRequest, opts ...grpc.CallOption) (*DeleteFeeResponse, error)
	CalculateFee(ctx context.Context, in *CalculateFeeRequest, opts ...grpc.CallOption) (*CalculateFeeResponse, error)
}

type feeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeeServiceClient(cc grpc.ClientConnInterface) FeeServiceClient {
	return &feeServiceClient{cc}
}

func (c *feeServiceClient) ListFees(ctx context.Context, in *ListFeesRequest, opts ...grpc.CallOption) (*ListFeesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeesResponse)
	err := c.cc.Invoke(ctx, FeeService_ListFees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feeServiceClient) CreateFee(ctx context.Context, in *CreateFeeRequest, opts ...grpc.CallOption) (*TransferFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferFeeResponse)
	err := c.cc.Invoke(ctx, FeeService_CreateFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feeServiceClient) UpdateFee(ctx context.Context, in *UpdateFeeRequest, opts ...grpc.CallOption) (*TransferFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferFeeResponse)
	err := c.cc.Invoke(ctx, FeeService_UpdateFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feeServiceClient) DeleteFee(ctx context.Context, in *DeleteFeeRequest, opts ...grpc.CallOption) (*DeleteFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFeeResponse)
	err := c.cc.Invoke(ctx, FeeService_DeleteFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feeServiceClient) CalculateFee(ctx context.Context, in *CalculateFeeRequest, opts ...grpc.CallOption) (*CalculateFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateFeeResponse)
	err := c.cc.Invoke(ctx, FeeService_CalculateFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeeServiceServer is the server API for FeeService service.
// All implementations must embed UnimplementedFeeServiceServer
// for forward compatibility.
type FeeServiceServer interface {
	ListFees(context.Context, *ListFeesRequest) (*ListFeesResponse, error)
	CreateFee(context.Context, *CreateFeeRequest) (*TransferFeeResponse, error)
	UpdateFee(context.Context, *UpdateFeeRequest) (*TransferFeeResponse, error)
	DeleteFee(context.Context, *DeleteFeeRequest) (*DeleteFeeResponse, error)
	CalculateFee(context.Context, *CalculateFeeRequest) (*CalculateFeeResponse, error)
	mustEmbedUnimplementedFeeServiceServer()
}

// UnimplementedFeeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeeServiceServer struct{}

func (UnimplementedFeeServiceServer) ListFees(context.Context, *ListFeesRequest) (*ListFeesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFees not implemented")
}
func (UnimplementedFeeServiceServer) CreateFee(context.Context, *CreateFeeRequest) (*TransferFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFee not implemented")
}
func (UnimplementedFeeServiceServer) UpdateFee(context.Context, *UpdateFeeRequest) (*TransferFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFee not implemented")
}
func (UnimplementedFeeServiceServer) DeleteFee(context.Context, *DeleteFeeRequest) (*DeleteFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFee not implemented")
}
func (UnimplementedFeeServiceServer) CalculateFee(context.Context, *CalculateFeeRequest) (*CalculateFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateFee not implemented")
}
func (UnimplementedFeeServiceServer) mustEmbedUnimplementedFeeServiceServer() {}
func (UnimplementedFeeServiceServer) testEmbeddedByValue()                    {}

// UnsafeFeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeeServiceServer will
// result in compilation errors.
type UnsafeFeeServiceServer interface {
	mustEmbedUnimplementedFeeServiceServer()
}

func RegisterFeeServiceServer(s grpc.ServiceRegistrar, srv FeeServiceServer) {
	// If the following call panics, it indicates UnimplementedFeeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeeService_ServiceDesc, srv)
}

func _FeeService_ListFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeeServiceServer).ListFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeeService_ListFees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeeServiceServer).ListFees(ctx, req.(*ListFeesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeeService_CreateFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeeServiceServer).CreateFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeeService_CreateFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeeServiceServer).CreateFee(ctx, req.(*CreateFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeeService_UpdateFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeeServiceServer).UpdateFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeeService_UpdateFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeeServiceServer).UpdateFee(ctx, req.(*UpdateFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeeService_DeleteFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeeServiceServer).DeleteFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeeService_DeleteFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeeServiceServer).DeleteFee(ctx, req.(*DeleteFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeeService_CalculateFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeeServiceServer).CalculateFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeeService_CalculateFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeeServiceServer).CalculateFee(ctx, req.(*CalculateFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeeService_ServiceDesc is the grpc.ServiceDesc for FeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.FeeService",
	HandlerType: (*FeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFees",
			Handler:    _FeeService_ListFees_Handler,
		},
		{
			MethodName: "CreateFee",
			Handler:    _FeeService_CreateFee_Handler,
		},
		{
			MethodName: "UpdateFee",
			Handler:    _FeeService_UpdateFee_Handler,
		},
		{
			MethodName: "DeleteFee",
			Handler:    _FeeService_DeleteFee_Handler,
		},
		{
			MethodName: "CalculateFee",
			Handler:    _FeeService_CalculateFee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction/transaction.proto",
}

const (
	PeerTxService_HandleNewTx_FullMethodName                    = "/transaction.PeerTxService/HandleNewTx"
	PeerTxService_HandleCommitTx_FullMethodName                 = "/transaction.PeerTxService/HandleCommitTx"
	PeerTxService_HandleRollbackTx_FullMethodName               = "/transaction.PeerTxService/HandleRollbackTx"
	PeerTxService_InitiateOutboundTx_FullMethodName             = "/transaction.PeerTxService/InitiateOutboundTx"
	PeerTxService_InitiateOutboundTxWithPostings_FullMethodName = "/transaction.PeerTxService/InitiateOutboundTxWithPostings"
	PeerTxService_GetTxStatus_FullMethodName                    = "/transaction.PeerTxService/GetTxStatus"
)

// PeerTxServiceClient is the client API for PeerTxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PeerTxService backs the SI-TX `POST /api/v3/interbank` endpoint. Each
// RPC corresponds to one messageType in the SI-TX envelope. Phase 2
// stubs the TX RPCs as Unimplemented; Phase 3 fills them in.
type PeerTxServiceClient interface {
	HandleNewTx(ctx context.Context, in *SiTxNewTxRequest, opts ...grpc.CallOption) (*SiTxVoteResponse, error)
	HandleCommitTx(ctx context.Context, in *SiTxCommitRequest, opts ...grpc.CallOption) (*SiTxAckResponse, error)
	HandleRollbackTx(ctx context.Context, in *SiTxRollbackRequest, opts ...grpc.CallOption) (*SiTxAckResponse, error)
	InitiateOutboundTx(ctx context.Context, in *SiTxInitiateRequest, opts ...grpc.CallOption) (*SiTxInitiateResponse, error)
	InitiateOutboundTxWithPostings(ctx context.Context, in *SiTxInitiateWithPostingsRequest, opts ...grpc.CallOption) (*SiTxInitiateResponse, error)
	// GetTxStatus allows a peer bank to query the status of a cross-bank
	// transaction by its transactionId (= our idempotenceKey). Used by the
	// Celina-5 CHECK_STATUS mechanism so both sides can resolve stuck sagas
	// when communication breaks mid-flight.
	GetTxStatus(ctx context.Context, in *GetTxStatusRequest, opts ...grpc.CallOption) (*GetTxStatusResponse, error)
}

type peerTxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerTxServiceClient(cc grpc.ClientConnInterface) PeerTxServiceClient {
	return &peerTxServiceClient{cc}
}

func (c *peerTxServiceClient) HandleNewTx(ctx context.Context, in *SiTxNewTxRequest, opts ...grpc.CallOption) (*SiTxVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SiTxVoteResponse)
	err := c.cc.Invoke(ctx, PeerTxService_HandleNewTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerTxServiceClient) HandleCommitTx(ctx context.Context, in *SiTxCommitRequest, opts ...grpc.CallOption) (*SiTxAckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SiTxAckResponse)
	err := c.cc.Invoke(ctx, PeerTxService_HandleCommitTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerTxServiceClient) HandleRollbackTx(ctx context.Context, in *SiTxRollbackRequest, opts ...grpc.CallOption) (*SiTxAckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SiTxAckResponse)
	err := c.cc.Invoke(ctx, PeerTxService_HandleRollbackTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerTxServiceClient) InitiateOutboundTx(ctx context.Context, in *SiTxInitiateRequest, opts ...grpc.CallOption) (*SiTxInitiateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SiTxInitiateResponse)
	err := c.cc.Invoke(ctx, PeerTxService_InitiateOutboundTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerTxServiceClient) InitiateOutboundTxWithPostings(ctx context.Context, in *SiTxInitiateWithPostingsRequest, opts ...grpc.CallOption) (*SiTxInitiateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SiTxInitiateResponse)
	err := c.cc.Invoke(ctx, PeerTxService_InitiateOutboundTxWithPostings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerTxServiceClient) GetTxStatus(ctx context.Context, in *GetTxStatusRequest, opts ...grpc.CallOption) (*GetTxStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTxStatusResponse)
	err := c.cc.Invoke(ctx, PeerTxService_GetTxStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerTxServiceServer is the server API for PeerTxService service.
// All implementations must embed UnimplementedPeerTxServiceServer
// for forward compatibility.
//
// PeerTxService backs the SI-TX `POST /api/v3/interbank` endpoint. Each
// RPC corresponds to one messageType in the SI-TX envelope. Phase 2
// stubs the TX RPCs as Unimplemented; Phase 3 fills them in.
type PeerTxServiceServer interface {
	HandleNewTx(context.Context, *SiTxNewTxRequest) (*SiTxVoteResponse, error)
	HandleCommitTx(context.Context, *SiTxCommitRequest) (*SiTxAckResponse, error)
	HandleRollbackTx(context.Context, *SiTxRollbackRequest) (*SiTxAckResponse, error)
	InitiateOutboundTx(context.Context, *SiTxInitiateRequest) (*SiTxInitiateResponse, error)
	InitiateOutboundTxWithPostings(context.Context, *SiTxInitiateWithPostingsRequest) (*SiTxInitiateResponse, error)
	// GetTxStatus allows a peer bank to query the status of a cross-bank
	// transaction by its transactionId (= our idempotenceKey). Used by the
	// Celina-5 CHECK_STATUS mechanism so both sides can resolve stuck sagas
	// when communication breaks mid-flight.
	GetTxStatus(context.Context, *GetTxStatusRequest) (*GetTxStatusResponse, error)
	mustEmbedUnimplementedPeerTxServiceServer()
}

// UnimplementedPeerTxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeerTxServiceServer struct{}

func (UnimplementedPeerTxServiceServer) HandleNewTx(context.Context, *SiTxNewTxRequest) (*SiTxVoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleNewTx not implemented")
}
func (UnimplementedPeerTxServiceServer) HandleCommitTx(context.Context, *SiTxCommitRequest) (*SiTxAckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleCommitTx not implemented")
}
func (UnimplementedPeerTxServiceServer) HandleRollbackTx(context.Context, *SiTxRollbackRequest) (*SiTxAckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleRollbackTx not implemented")
}
func (UnimplementedPeerTxServiceServer) InitiateOutboundTx(context.Context, *SiTxInitiateRequest) (*SiTxInitiateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateOutboundTx not implemented")
}
func (UnimplementedPeerTxServiceServer) InitiateOutboundTxWithPostings(context.Context, *SiTxInitiateWithPostingsRequest) (*SiTxInitiateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateOutboundTxWithPostings not implemented")
}
func (UnimplementedPeerTxServiceServer) GetTxStatus(context.Context, *GetTxStatusRequest) (*GetTxStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTxStatus not implemented")
}
func (UnimplementedPeerTxServiceServer) mustEmbedUnimplementedPeerTxServiceServer() {}
func (UnimplementedPeerTxServiceServer) testEmbeddedByValue()                       {}

// UnsafePeerTxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerTxServiceServer will
// result in compilation errors.
type UnsafePeerTxServiceServer interface {
	mustEmbedUnimplementedPeerTxServiceServer()
}

func RegisterPeerTxServiceServer(s grpc.ServiceRegistrar, srv PeerTxServiceServer) {
	// If the following call panics, it indicates UnimplementedPeerTxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeerTxService_ServiceDesc, srv)
}

func _PeerTxService_HandleNewTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiTxNewTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerTxServiceServer).HandleNewTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerTxService_HandleNewTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerTxServiceServer).HandleNewTx(ctx, req.(*SiTxNewTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerTxService_HandleCommitTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiTxCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerTxServiceServer).HandleCommitTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerTxService_HandleCommitTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerTxServiceServer).HandleCommitTx(ctx, req.(*SiTxCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerTxService_HandleRollbackTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiTxRollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerTxServiceServer).HandleRollbackTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerTxService_HandleRollbackTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerTxServiceServer).HandleRollbackTx(ctx, req.(*SiTxRollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerTxService_InitiateOutboundTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiTxInitiateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerTxServiceServer).InitiateOutboundTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerTxService_InitiateOutboundTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerTxServiceServer).InitiateOutboundTx(ctx, req.(*SiTxInitiateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerTxService_InitiateOutboundTxWithPostings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiTxInitiateWithPostingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerTxServiceServer).InitiateOutboundTxWithPostings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerTxService_InitiateOutboundTxWithPostings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerTxServiceServer).InitiateOutboundTxWithPostings(ctx, req.(*SiTxInitiateWithPostingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerTxService_GetTxStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerTxServiceServer).GetTxStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerTxService_GetTxStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerTxServiceServer).GetTxStatus(ctx, req.(*GetTxStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeerTxService_ServiceDesc is the grpc.ServiceDesc for PeerTxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerTxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.PeerTxService",
	HandlerType: (*PeerTxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleNewTx",
			Handler:    _PeerTxService_HandleNewTx_Handler,
		},
		{
			MethodName: "HandleCommitTx",
			Handler:    _PeerTxService_HandleCommitTx_Handler,
		},
		{
			MethodName: "HandleRollbackTx",
			Handler:    _PeerTxService_HandleRollbackTx_Handler,
		},
		{
			MethodName: "InitiateOutboundTx",
			Handler:    _PeerTxService_InitiateOutboundTx_Handler,
		},
		{
			MethodName: "InitiateOutboundTxWithPostings",
			Handler:    _PeerTxService_InitiateOutboundTxWithPostings_Handler,
		},
		{
			MethodName: "GetTxStatus",
			Handler:    _PeerTxService_GetTxStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction/transaction.proto",
}

const (
	PeerBankAdminService_ListPeerBanks_FullMethodName         = "/transaction.PeerBankAdminService/ListPeerBanks"
	PeerBankAdminService_GetPeerBank_FullMethodName           = "/transaction.PeerBankAdminService/GetPeerBank"
	PeerBankAdminService_CreatePeerBank_FullMethodName        = "/transaction.PeerBankAdminService/CreatePeerBank"
	PeerBankAdminService_UpdatePeerBank_FullMethodName        = "/transaction.PeerBankAdminService/UpdatePeerBank"
	PeerBankAdminService_DeletePeerBank_FullMethodName        = "/transaction.PeerBankAdminService/DeletePeerBank"
	PeerBankAdminService_ResolvePeerByAPIToken_FullMethodName = "/transaction.PeerBankAdminService/ResolvePeerByAPIToken"
	PeerBankAdminService_ResolvePeerByBankCode_FullMethodName = "/transaction.PeerBankAdminService/ResolvePeerByBankCode"
)

// PeerBankAdminServiceClient is the client API for PeerBankAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PeerBankAdminService is the runtime-editable peer-bank registry. Lets
// admins add/update/remove peer banks without redeploys. Gated by the
// peer_banks.manage.any permission.
type PeerBankAdminServiceClient interface {
	ListPeerBanks(ctx context.Context, in *ListPeerBanksRequest, opts ...grpc.CallOption) (*ListPeerBanksResponse, error)
	GetPeerBank(ctx context.Context, in *GetPeerBankRequest, opts ...grpc.CallOption) (*PeerBank, error)
	CreatePeerBank(ctx context.Context, in *CreatePeerBankRequest, opts ...grpc.CallOption) (*PeerBank, error)
	UpdatePeerBank(ctx context.Context, in *UpdatePeerBankRequest, opts ...grpc.CallOption) (*PeerBank, error)
	DeletePeerBank(ctx context.Context, in *DeletePeerBankRequest, opts ...grpc.CallOption) (*DeletePeerBankResponse, error)
	// Phase 3 internal RPCs (Celina 5 SI-TX): return full peer-bank record
	// including HMAC keys + plaintext API token. NOT exposed via REST —
	// gateway-internal use only.
	ResolvePeerByAPIToken(ctx context.Context, in *ResolvePeerByAPITokenRequest, opts ...grpc.CallOption) (*ResolvePeerByAPITokenResponse, error)
	ResolvePeerByBankCode(ctx context.Context, in *ResolvePeerByBankCodeRequest, opts ...grpc.CallOption) (*ResolvePeerByBankCodeResponse, error)
}

type peerBankAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerBankAdminServiceClient(cc grpc.ClientConnInterface) PeerBankAdminServiceClient {
	return &peerBankAdminServiceClient{cc}
}

func (c *peerBankAdminServiceClient) ListPeerBanks(ctx context.Context, in *ListPeerBanksRequest, opts ...grpc.CallOption) (*ListPeerBanksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPeerBanksResponse)
	err := c.cc.Invoke(ctx, PeerBankAdminService_ListPeerBanks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerBankAdminServiceClient) GetPeerBank(ctx context.Context, in *GetPeerBankRequest, opts ...grpc.CallOption) (*PeerBank, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerBank)
	err := c.cc.Invoke(ctx, PeerBankAdminService_GetPeerBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerBankAdminServiceClient) CreatePeerBank(ctx context.Context, in *CreatePeerBankRequest, opts ...grpc.CallOption) (*PeerBank, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerBank)
	err := c.cc.Invoke(ctx, PeerBankAdminService_CreatePeerBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerBankAdminServiceClient) UpdatePeerBank(ctx context.Context, in *UpdatePeerBankRequest, opts ...grpc.CallOption) (*PeerBank, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerBank)
	err := c.cc.Invoke(ctx, PeerBankAdminService_UpdatePeerBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerBankAdminServiceClient) DeletePeerBank(ctx context.Context, in *DeletePeerBankRequest, opts ...grpc.CallOption) (*DeletePeerBankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePeerBankResponse)
	err := c.cc.Invoke(ctx, PeerBankAdminService_DeletePeerBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerBankAdminServiceClient) ResolvePeerByAPIToken(ctx context.Context, in *ResolvePeerByAPITokenRequest, opts ...grpc.CallOption) (*ResolvePeerByAPITokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolvePeerByAPITokenResponse)
	err := c.cc.Invoke(ctx, PeerBankAdminService_ResolvePeerByAPIToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerBankAdminServiceClient) ResolvePeerByBankCode(ctx context.Context, in *ResolvePeerByBankCodeRequest, opts ...grpc.CallOption) (*ResolvePeerByBankCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolvePeerByBankCodeResponse)
	err := c.cc.Invoke(ctx, PeerBankAdminService_ResolvePeerByBankCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerBankAdminServiceServer is the server API for PeerBankAdminService service.
// All implementations must embed UnimplementedPeerBankAdminServiceServer
// for forward compatibility.
//
// PeerBankAdminService is the runtime-editable peer-bank registry. Lets
// admins add/update/remove peer banks without redeploys. Gated by the
// peer_banks.manage.any permission.
type PeerBankAdminServiceServer interface {
	ListPeerBanks(context.Context, *ListPeerBanksRequest) (*ListPeerBanksResponse, error)
	GetPeerBank(context.Context, *GetPeerBankRequest) (*PeerBank, error)
	CreatePeerBank(context.Context, *CreatePeerBankRequest) (*PeerBank, error)
	UpdatePeerBank(context.Context, *UpdatePeerBankRequest) (*PeerBank, error)
	DeletePeerBank(context.Context, *DeletePeerBankRequest) (*DeletePeerBankResponse, error)
	// Phase 3 internal RPCs (Celina 5 SI-TX): return full peer-bank record
	// including HMAC keys + plaintext API token. NOT exposed via REST —
	// gateway-internal use only.
	ResolvePeerByAPIToken(context.Context, *ResolvePeerByAPITokenRequest) (*ResolvePeerByAPITokenResponse, error)
	ResolvePeerByBankCode(context.Context, *ResolvePeerByBankCodeRequest) (*ResolvePeerByBankCodeResponse, error)
	mustEmbedUnimplementedPeerBankAdminServiceServer()
}

// UnimplementedPeerBankAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeerBankAdminServiceServer struct{}

func (UnimplementedPeerBankAdminServiceServer) ListPeerBanks(context.Context, *ListPeerBanksRequest) (*ListPeerBanksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPeerBanks not implemented")
}
func (UnimplementedPeerBankAdminServiceServer) GetPeerBank(context.Context, *GetPeerBankRequest) (*PeerBank, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPeerBank not implemented")
}
func (UnimplementedPeerBankAdminServiceServer) CreatePeerBank(context.Context, *CreatePeerBankRequest) (*PeerBank, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePeerBank not implemented")
}
func (UnimplementedPeerBankAdminServiceServer) UpdatePeerBank(context.Context, *UpdatePeerBankRequest) (*PeerBank, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePeerBank not implemented")
}
func (UnimplementedPeerBankAdminServiceServer) DeletePeerBank(context.Context, *DeletePeerBankRequest) (*DeletePeerBankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePeerBank not implemented")
}
func (UnimplementedPeerBankAdminServiceServer) ResolvePeerByAPIToken(context.Context, *ResolvePeerByAPITokenRequest) (*ResolvePeerByAPITokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolvePeerByAPIToken not implemented")
}
func (UnimplementedPeerBankAdminServiceServer) ResolvePeerByBankCode(context.Context, *ResolvePeerByBankCodeRequest) (*ResolvePeerByBankCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolvePeerByBankCode not implemented")
}
func (UnimplementedPeerBankAdminServiceServer) mustEmbedUnimplementedPeerBankAdminServiceServer() {}
func (UnimplementedPeerBankAdminServiceServer) testEmbeddedByValue()                              {}

// UnsafePeerBankAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerBankAdminServiceServer will
// result in compilation errors.
type UnsafePeerBankAdminServiceServer interface {
	mustEmbedUnimplementedPeerBankAdminServiceServer()
}

func RegisterPeerBankAdminServiceServer(s grpc.ServiceRegistrar, srv PeerBankAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedPeerBankAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeerBankAdminService_ServiceDesc, srv)
}

func _PeerBankAdminService_ListPeerBanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeerBanksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerBankAdminServiceServer).ListPeerBanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerBankAdminService_ListPeerBanks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerBankAdminServiceServer).ListPeerBanks(ctx, req.(*ListPeerBanksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerBankAdminService_GetPeerBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeerBankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerBankAdminServiceServer).GetPeerBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerBankAdminService_GetPeerBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerBankAdminServiceServer).GetPeerBank(ctx, req.(*GetPeerBankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerBankAdminService_CreatePeerBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePeerBankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerBankAdminServiceServer).CreatePeerBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerBankAdminService_CreatePeerBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerBankAdminServiceServer).CreatePeerBank(ctx, req.(*CreatePeerBankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerBankAdminService_UpdatePeerBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePeerBankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerBankAdminServiceServer).UpdatePeerBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerBankAdminService_UpdatePeerBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerBankAdminServiceServer).UpdatePeerBank(ctx, req.(*UpdatePeerBankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerBankAdminService_DeletePeerBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePeerBankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerBankAdminServiceServer).DeletePeerBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerBankAdminService_DeletePeerBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerBankAdminServiceServer).DeletePeerBank(ctx, req.(*DeletePeerBankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerBankAdminService_ResolvePeerByAPIToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvePeerByAPITokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerBankAdminServiceServer).ResolvePeerByAPIToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerBankAdminService_ResolvePeerByAPIToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerBankAdminServiceServer).ResolvePeerByAPIToken(ctx, req.(*ResolvePeerByAPITokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerBankAdminService_ResolvePeerByBankCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvePeerByBankCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerBankAdminServiceServer).ResolvePeerByBankCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerBankAdminService_ResolvePeerByBankCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerBankAdminServiceServer).ResolvePeerByBankCode(ctx, req.(*ResolvePeerByBankCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeerBankAdminService_ServiceDesc is the grpc.ServiceDesc for PeerBankAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerBankAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.PeerBankAdminService",
	HandlerType: (*PeerBankAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPeerBanks",
			Handler:    _PeerBankAdminService_ListPeerBanks_Handler,
		},
		{
			MethodName: "GetPeerBank",
			Handler:    _PeerBankAdminService_GetPeerBank_Handler,
		},
		{
			MethodName: "CreatePeerBank",
			Handler:    _PeerBankAdminService_CreatePeerBank_Handler,
		},
		{
			MethodName: "UpdatePeerBank",
			Handler:    _PeerBankAdminService_UpdatePeerBank_Handler,
		},
		{
			MethodName: "DeletePeerBank",
			Handler:    _PeerBankAdminService_DeletePeerBank_Handler,
		},
		{
			MethodName: "ResolvePeerByAPIToken",
			Handler:    _PeerBankAdminService_ResolvePeerByAPIToken_Handler,
		},
		{
			MethodName: "ResolvePeerByBankCode",
			Handler:    _PeerBankAdminService_ResolvePeerByBankCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction/transaction.proto",
}
