// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: client/client.proto

package clientpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientService_CreateClient_FullMethodName      = "/client.ClientService/CreateClient"
	ClientService_GetClient_FullMethodName         = "/client.ClientService/GetClient"
	ClientService_GetClientByEmail_FullMethodName  = "/client.ClientService/GetClientByEmail"
	ClientService_ListClients_FullMethodName       = "/client.ClientService/ListClients"
	ClientService_UpdateClient_FullMethodName      = "/client.ClientService/UpdateClient"
	ClientService_ListChangelog_FullMethodName     = "/client.ClientService/ListChangelog"
	ClientService_ListAllChangelogs_FullMethodName = "/client.ClientService/ListAllChangelogs"
)

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientServiceClient interface {
	CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*ClientResponse, error)
	GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*ClientResponse, error)
	GetClientByEmail(ctx context.Context, in *GetClientByEmailRequest, opts ...grpc.CallOption) (*ClientResponse, error)
	ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error)
	UpdateClient(ctx context.Context, in *UpdateClientRequest, opts ...grpc.CallOption) (*ClientResponse, error)
	// Audit-trail reads. Returns changelog rows scoped by entity_type +
	// entity_id; pagination matches list endpoints (1-based page).
	ListChangelog(ctx context.Context, in *ListChangelogRequest, opts ...grpc.CallOption) (*ListChangelogResponse, error)
	// ListAllChangelogs returns every changelog row for this service (global
	// audit view, admin-only). Supports optional filters: since/until (unix
	// seconds), actor_id (changed_by), action string, and pagination.
	ListAllChangelogs(ctx context.Context, in *ListAllChangelogsRequest, opts ...grpc.CallOption) (*ListAllChangelogsResponse, error)
}

type clientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServiceClient(cc grpc.ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*ClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientResponse)
	err := c.cc.Invoke(ctx, ClientService_CreateClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*ClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientResponse)
	err := c.cc.Invoke(ctx, ClientService_GetClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) GetClientByEmail(ctx context.Context, in *GetClientByEmailRequest, opts ...grpc.CallOption) (*ClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientResponse)
	err := c.cc.Invoke(ctx, ClientService_GetClientByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClientsResponse)
	err := c.cc.Invoke(ctx, ClientService_ListClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) UpdateClient(ctx context.Context, in *UpdateClientRequest, opts ...grpc.CallOption) (*ClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientResponse)
	err := c.cc.Invoke(ctx, ClientService_UpdateClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) ListChangelog(ctx context.Context, in *ListChangelogRequest, opts ...grpc.CallOption) (*ListChangelogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChangelogResponse)
	err := c.cc.Invoke(ctx, ClientService_ListChangelog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) ListAllChangelogs(ctx context.Context, in *ListAllChangelogsRequest, opts ...grpc.CallOption) (*ListAllChangelogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllChangelogsResponse)
	err := c.cc.Invoke(ctx, ClientService_ListAllChangelogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
// All implementations must embed UnimplementedClientServiceServer
// for forward compatibility.
type ClientServiceServer interface {
	CreateClient(context.Context, *CreateClientRequest) (*ClientResponse, error)
	GetClient(context.Context, *GetClientRequest) (*ClientResponse, error)
	GetClientByEmail(context.Context, *GetClientByEmailRequest) (*ClientResponse, error)
	ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error)
	UpdateClient(context.Context, *UpdateClientRequest) (*ClientResponse, error)
	// Audit-trail reads. Returns changelog rows scoped by entity_type +
	// entity_id; pagination matches list endpoints (1-based page).
	ListChangelog(context.Context, *ListChangelogRequest) (*ListChangelogResponse, error)
	// ListAllChangelogs returns every changelog row for this service (global
	// audit view, admin-only). Supports optional filters: since/until (unix
	// seconds), actor_id (changed_by), action string, and pagination.
	ListAllChangelogs(context.Context, *ListAllChangelogsRequest) (*ListAllChangelogsResponse, error)
	mustEmbedUnimplementedClientServiceServer()
}

// UnimplementedClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientServiceServer struct{}

func (UnimplementedClientServiceServer) CreateClient(context.Context, *CreateClientRequest) (*ClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateClient not implemented")
}
func (UnimplementedClientServiceServer) GetClient(context.Context, *GetClientRequest) (*ClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClient not implemented")
}
func (UnimplementedClientServiceServer) GetClientByEmail(context.Context, *GetClientByEmailRequest) (*ClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClientByEmail not implemented")
}
func (UnimplementedClientServiceServer) ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClients not implemented")
}
func (UnimplementedClientServiceServer) UpdateClient(context.Context, *UpdateClientRequest) (*ClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateClient not implemented")
}
func (UnimplementedClientServiceServer) ListChangelog(context.Context, *ListChangelogRequest) (*ListChangelogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChangelog not implemented")
}
func (UnimplementedClientServiceServer) ListAllChangelogs(context.Context, *ListAllChangelogsRequest) (*ListAllChangelogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllChangelogs not implemented")
}
func (UnimplementedClientServiceServer) mustEmbedUnimplementedClientServiceServer() {}
func (UnimplementedClientServiceServer) testEmbeddedByValue()                       {}

// UnsafeClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServiceServer will
// result in compilation errors.
type UnsafeClientServiceServer interface {
	mustEmbedUnimplementedClientServiceServer()
}

func RegisterClientServiceServer(s grpc.ServiceRegistrar, srv ClientServiceServer) {
	// If the following call panics, it indicates UnimplementedClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientService_ServiceDesc, srv)
}

func _ClientService_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_CreateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).CreateClient(ctx, req.(*CreateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_GetClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).GetClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_GetClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).GetClient(ctx, req.(*GetClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_GetClientByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).GetClientByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_GetClientByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).GetClientByEmail(ctx, req.(*GetClientByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_ListClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).ListClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_ListClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).ListClients(ctx, req.(*ListClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_UpdateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).UpdateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_UpdateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).UpdateClient(ctx, req.(*UpdateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_ListChangelog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChangelogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).ListChangelog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_ListChangelog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).ListChangelog(ctx, req.(*ListChangelogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_ListAllChangelogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllChangelogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).ListAllChangelogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_ListAllChangelogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).ListAllChangelogs(ctx, req.(*ListAllChangelogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientService_ServiceDesc is the grpc.ServiceDesc for ClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "client.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClient",
			Handler:    _ClientService_CreateClient_Handler,
		},
		{
			MethodName: "GetClient",
			Handler:    _ClientService_GetClient_Handler,
		},
		{
			MethodName: "GetClientByEmail",
			Handler:    _ClientService_GetClientByEmail_Handler,
		},
		{
			MethodName: "ListClients",
			Handler:    _ClientService_ListClients_Handler,
		},
		{
			MethodName: "UpdateClient",
			Handler:    _ClientService_UpdateClient_Handler,
		},
		{
			MethodName: "ListChangelog",
			Handler:    _ClientService_ListChangelog_Handler,
		},
		{
			MethodName: "ListAllChangelogs",
			Handler:    _ClientService_ListAllChangelogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client/client.proto",
}

const (
	ClientLimitService_GetClientLimits_FullMethodName = "/client.ClientLimitService/GetClientLimits"
	ClientLimitService_SetClientLimits_FullMethodName = "/client.ClientLimitService/SetClientLimits"
)

// ClientLimitServiceClient is the client API for ClientLimitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientLimitServiceClient interface {
	GetClientLimits(ctx context.Context, in *GetClientLimitRequest, opts ...grpc.CallOption) (*ClientLimitResponse, error)
	SetClientLimits(ctx context.Context, in *SetClientLimitRequest, opts ...grpc.CallOption) (*ClientLimitResponse, error)
}

type clientLimitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientLimitServiceClient(cc grpc.ClientConnInterface) ClientLimitServiceClient {
	return &clientLimitServiceClient{cc}
}

func (c *clientLimitServiceClient) GetClientLimits(ctx context.Context, in *GetClientLimitRequest, opts ...grpc.CallOption) (*ClientLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientLimitResponse)
	err := c.cc.Invoke(ctx, ClientLimitService_GetClientLimits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientLimitServiceClient) SetClientLimits(ctx context.Context, in *SetClientLimitRequest, opts ...grpc.CallOption) (*ClientLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientLimitResponse)
	err := c.cc.Invoke(ctx, ClientLimitService_SetClientLimits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientLimitServiceServer is the server API for ClientLimitService service.
// All implementations must embed UnimplementedClientLimitServiceServer
// for forward compatibility.
type ClientLimitServiceServer interface {
	GetClientLimits(context.Context, *GetClientLimitRequest) (*ClientLimitResponse, error)
	SetClientLimits(context.Context, *SetClientLimitRequest) (*ClientLimitResponse, error)
	mustEmbedUnimplementedClientLimitServiceServer()
}

// UnimplementedClientLimitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientLimitServiceServer struct{}

func (UnimplementedClientLimitServiceServer) GetClientLimits(context.Context, *GetClientLimitRequest) (*ClientLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClientLimits not implemented")
}
func (UnimplementedClientLimitServiceServer) SetClientLimits(context.Context, *SetClientLimitRequest) (*ClientLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetClientLimits not implemented")
}
func (UnimplementedClientLimitServiceServer) mustEmbedUnimplementedClientLimitServiceServer() {}
func (UnimplementedClientLimitServiceServer) testEmbeddedByValue()                            {}

// UnsafeClientLimitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientLimitServiceServer will
// result in compilation errors.
type UnsafeClientLimitServiceServer interface {
	mustEmbedUnimplementedClientLimitServiceServer()
}

func RegisterClientLimitServiceServer(s grpc.ServiceRegistrar, srv ClientLimitServiceServer) {
	// If the following call panics, it indicates UnimplementedClientLimitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientLimitService_ServiceDesc, srv)
}

func _ClientLimitService_GetClientLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientLimitServiceServer).GetClientLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientLimitService_GetClientLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientLimitServiceServer).GetClientLimits(ctx, req.(*GetClientLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientLimitService_SetClientLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetClientLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientLimitServiceServer).SetClientLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientLimitService_SetClientLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientLimitServiceServer).SetClientLimits(ctx, req.(*SetClientLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientLimitService_ServiceDesc is the grpc.ServiceDesc for ClientLimitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientLimitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "client.ClientLimitService",
	HandlerType: (*ClientLimitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClientLimits",
			Handler:    _ClientLimitService_GetClientLimits_Handler,
		},
		{
			MethodName: "SetClientLimits",
			Handler:    _ClientLimitService_SetClientLimits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client/client.proto",
}
