// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: admin/admin_cron.proto

package adminpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminCron_ListCrons_FullMethodName   = "/admin.AdminCron/ListCrons"
	AdminCron_GetCron_FullMethodName     = "/admin.AdminCron/GetCron"
	AdminCron_TriggerCron_FullMethodName = "/admin.AdminCron/TriggerCron"
	AdminCron_PauseCron_FullMethodName   = "/admin.AdminCron/PauseCron"
	AdminCron_ResumeCron_FullMethodName  = "/admin.AdminCron/ResumeCron"
)

// AdminCronClient is the client API for AdminCron service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminCronClient interface {
	ListCrons(ctx context.Context, in *ListCronsRequest, opts ...grpc.CallOption) (*ListCronsResponse, error)
	GetCron(ctx context.Context, in *GetCronRequest, opts ...grpc.CallOption) (*CronInfoMsg, error)
	TriggerCron(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*CronCtrlResponse, error)
	PauseCron(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*CronCtrlResponse, error)
	ResumeCron(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*CronCtrlResponse, error)
}

type adminCronClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminCronClient(cc grpc.ClientConnInterface) AdminCronClient {
	return &adminCronClient{cc}
}

func (c *adminCronClient) ListCrons(ctx context.Context, in *ListCronsRequest, opts ...grpc.CallOption) (*ListCronsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCronsResponse)
	err := c.cc.Invoke(ctx, AdminCron_ListCrons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCronClient) GetCron(ctx context.Context, in *GetCronRequest, opts ...grpc.CallOption) (*CronInfoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronInfoMsg)
	err := c.cc.Invoke(ctx, AdminCron_GetCron_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCronClient) TriggerCron(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*CronCtrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronCtrlResponse)
	err := c.cc.Invoke(ctx, AdminCron_TriggerCron_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCronClient) PauseCron(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*CronCtrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronCtrlResponse)
	err := c.cc.Invoke(ctx, AdminCron_PauseCron_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCronClient) ResumeCron(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*CronCtrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronCtrlResponse)
	err := c.cc.Invoke(ctx, AdminCron_ResumeCron_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminCronServer is the server API for AdminCron service.
// All implementations must embed UnimplementedAdminCronServer
// for forward compatibility.
type AdminCronServer interface {
	ListCrons(context.Context, *ListCronsRequest) (*ListCronsResponse, error)
	GetCron(context.Context, *GetCronRequest) (*CronInfoMsg, error)
	TriggerCron(context.Context, *TriggerRequest) (*CronCtrlResponse, error)
	PauseCron(context.Context, *PauseRequest) (*CronCtrlResponse, error)
	ResumeCron(context.Context, *ResumeRequest) (*CronCtrlResponse, error)
	mustEmbedUnimplementedAdminCronServer()
}

// UnimplementedAdminCronServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminCronServer struct{}

func (UnimplementedAdminCronServer) ListCrons(context.Context, *ListCronsRequest) (*ListCronsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCrons not implemented")
}
func (UnimplementedAdminCronServer) GetCron(context.Context, *GetCronRequest) (*CronInfoMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCron not implemented")
}
func (UnimplementedAdminCronServer) TriggerCron(context.Context, *TriggerRequest) (*CronCtrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerCron not implemented")
}
func (UnimplementedAdminCronServer) PauseCron(context.Context, *PauseRequest) (*CronCtrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseCron not implemented")
}
func (UnimplementedAdminCronServer) ResumeCron(context.Context, *ResumeRequest) (*CronCtrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeCron not implemented")
}
func (UnimplementedAdminCronServer) mustEmbedUnimplementedAdminCronServer() {}
func (UnimplementedAdminCronServer) testEmbeddedByValue()                   {}

// UnsafeAdminCronServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminCronServer will
// result in compilation errors.
type UnsafeAdminCronServer interface {
	mustEmbedUnimplementedAdminCronServer()
}

func RegisterAdminCronServer(s grpc.ServiceRegistrar, srv AdminCronServer) {
	// If the following call panics, it indicates UnimplementedAdminCronServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminCron_ServiceDesc, srv)
}

func _AdminCron_ListCrons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCronsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCronServer).ListCrons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCron_ListCrons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCronServer).ListCrons(ctx, req.(*ListCronsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCron_GetCron_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCronRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCronServer).GetCron(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCron_GetCron_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCronServer).GetCron(ctx, req.(*GetCronRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCron_TriggerCron_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCronServer).TriggerCron(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCron_TriggerCron_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCronServer).TriggerCron(ctx, req.(*TriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCron_PauseCron_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCronServer).PauseCron(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCron_PauseCron_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCronServer).PauseCron(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCron_ResumeCron_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCronServer).ResumeCron(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCron_ResumeCron_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCronServer).ResumeCron(ctx, req.(*ResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminCron_ServiceDesc is the grpc.ServiceDesc for AdminCron service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminCron_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminCron",
	HandlerType: (*AdminCronServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCrons",
			Handler:    _AdminCron_ListCrons_Handler,
		},
		{
			MethodName: "GetCron",
			Handler:    _AdminCron_GetCron_Handler,
		},
		{
			MethodName: "TriggerCron",
			Handler:    _AdminCron_TriggerCron_Handler,
		},
		{
			MethodName: "PauseCron",
			Handler:    _AdminCron_PauseCron_Handler,
		},
		{
			MethodName: "ResumeCron",
			Handler:    _AdminCron_ResumeCron_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/admin_cron.proto",
}
