#!/usr/bin/env python3
"""Generate self-contained per-bank docker-compose files for cross-bank testing.

Reads the root docker-compose.yml and emits bank1/docker-compose.yml and
bank2/docker-compose.yml. Each is an independent stack (its own project name →
namespaced containers/volumes/networks) that:
  - reuses the root-built images (image: exbanka-1-backend-<svc>:latest) but
    keeps a build section (context: ..) so `docker compose ... up --build` still
    works from the bank folder;
  - publishes ONLY the api-gateway host port (per bank) so the two stacks don't
    collide on host ports — services reach each other over the compose network;
  - reads OWN_BANK_CODE / gateway port / secrets from the sibling .env.

Run from repo root:  python3 scripts/gen-bank-stacks.py
"""
import copy
import yaml

ROOT = "docker-compose.yml"
PROJECT_IMAGE_PREFIX = "exbanka-1-backend"  # root compose project → image prefix

BANKS = [
    {"folder": "bank1", "name": "bank1", "gateway_host_port": 8080},
    {"folder": "bank2", "name": "bank2", "gateway_host_port": 8081},
]


def load_root():
    with open(ROOT) as f:
        return yaml.safe_load(f)


def transform(root, bank):
    doc = copy.deepcopy(root)
    doc.pop("name", None)
    out = {"name": bank["name"]}
    # keep top-level keys ordered: name, services, volumes, networks
    out["services"] = doc.get("services", {})
    for svc_name, svc in out["services"].items():
        # container_name would collide across projects — drop it, let compose
        # auto-name with the <project>- prefix.
        svc.pop("container_name", None)

        # Observability (prometheus/grafana) is opt-in for the bank test stacks
        # — nothing depends on them. Start with `--profile observability` if
        # wanted; otherwise they stay down to save resources running 2 stacks.
        if svc_name in ("prometheus", "grafana"):
            svc["profiles"] = ["observability"]

        # Services that build from source: pin to the shared root-built image
        # and rewrite the build context to the repo root (one level up from the
        # bank folder) so an explicit --build still works.
        if "build" in svc:
            svc["image"] = f"{PROJECT_IMAGE_PREFIX}-{svc_name}:latest"
            b = svc["build"]
            if isinstance(b, dict):
                if b.get("context", ".") == ".":
                    b["context"] = ".."
            else:
                svc["build"] = {"context": "..", "dockerfile": f"{svc_name}/Dockerfile"}

        # Strip ALL published host ports except the api-gateway (remapped per
        # bank). Internal service-to-service traffic uses the compose network.
        if svc_name == "api-gateway":
            svc["ports"] = [f"{bank['gateway_host_port']}:8080"]
            # gateway may resolve peers over host.docker.internal in some paths
            eh = svc.get("extra_hosts", [])
            if "host.docker.internal:host-gateway" not in eh:
                eh.append("host.docker.internal:host-gateway")
            svc["extra_hosts"] = eh
        else:
            svc.pop("ports", None)

    if "volumes" in doc:
        out["volumes"] = doc["volumes"]
    if "networks" in doc:
        out["networks"] = doc["networks"]
    return out


def main():
    root = load_root()
    for bank in BANKS:
        doc = transform(root, bank)
        path = f"{bank['folder']}/docker-compose.yml"
        header = (
            "# GENERATED by scripts/gen-bank-stacks.py — do not edit by hand.\n"
            f"# {bank['name']} cross-bank test instance. Reuses root-built images\n"
            f"# ({PROJECT_IMAGE_PREFIX}-*:latest). Run from this folder:\n"
            f"#   docker compose up -d        (project name '{bank['name']}')\n"
            f"# Gateway published on host :{bank['gateway_host_port']}.\n"
        )
        with open(path, "w") as f:
            f.write(header)
            yaml.safe_dump(doc, f, sort_keys=False, default_flow_style=False, width=4096)
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
